### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by carlosamus123** [Andre0512/hon#101]
**Describe the bug**
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble
On initial setup of the integration

**To Reproduce**
1. Install Via HACs or Manually
2. Integrations > Add  
3. "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

**Expected behavior**
Options to login via Hon?

**Screenshots**
![image](https://github.com/Andre0512/hon/assets/19592298/c21bb8aa-2572-43bb-957c-6c3a9679e4dd).

**Environment (please complete the following information):**
 - Home Assistant Version: 2023.7.2
 - hOn Integration Version [e.g. `0.8.1`, can be found in HACS or device log]
 - pyhOn Version 1.4.0

**Additional context**
n/a

**Home Assistant Logs**
n/a

**Device Log**
n/a

**Data Archive**
n/a

**Comment by Andre0512** [comment]
Hey, this looks strange, I didn't see anything like this before :thinking: 
Can you see something in the home assistant logs?

**Comment by carlosamus123** [comment]
It's fine now. I initially used HACS but tried manual and it worked   might
have been a hiccup on the download
