### ISSUE TITLE
Hoower hwash 550 energy consumption

### ISSUE THREAD

**Issue by Ices-Eyes** [Andre0512/hon#107]
Hi,
I've already sended the log data to the hon-test-data page for my washing machine. BTW, it seems that there is no sensor for the energy consumption... Any advice?
Thanks

**Comment by Andre0512** [comment]
Hey @Ices-Eyes, I had a closer look. Your device doesn't expose any energy consumption data, so there is nothing to show... :slightly_smiling_face:
