### ISSUE TITLE
AC 4U85S2SR3FA with AS25PBAHRA - missing features

### ISSUE THREAD

**Issue by bennatzen** [Andre0512/hon#108]
[ac_343.zip](https://github.com/Andre0512/hon/files/12454024/ac_343.zip)

Hi there.

The 4U85S2SR3FA is a multisplit with AS25PBAHRA indoor devices.

Your integration is working but I miss some features like:

- the vertical Fan Positions:

- Pos 1
- Pos 2
- Pos 3

- Pos 4

> ========== AC - Büro ==========
> data:
>   additional_data:
>     dictionaryId: 181
>   appliance:
>     PK: user#eu-west-1:1e6574bd-8274-465d-94d6-0eb704fbe0a5
>     SK: app#a8-48-fa-36-e7-34
>     SK_Secondary: AC#selfClean56#2023-01-14
>     applianceId: a8-48-fa-36-e7-34#2022-11-15T19:19:26Z
>     applianceModelId: 343
>     applianceStatus: 1
>     applianceTypeId: 11
>     applianceTypeName: AC
>     attributes:
>       acuVersion: 0.0.0
>       chipset: 1
>       dictionaryId: 181
>       eppParserSet: 1
>       fwLabel: iotfw_epp
>       idfVersion: 4.4.4
>       kernelVersion: 10.4.3
>       lang: it-IT
>       uiVersion: 06.26.00
>     brand: haier
>     code: AABF10E0000
>     connectivity: wifi|ble
>     coords:
>       lat: 51.0935868
>       lng: 7.1842247
>     eepromId: 41
>     eepromName: no_eeprom
>     enrollmentDate: 2022-11-15T19:19:26.527Z
>     firstEnrollment: True
>     firstEnrollmentTBC: True
>     fwVersion: 5.15.0
>     id: 343
>     lastUpdate: 2023-06-19T10:40:59Z
>     macAddress: a8-48-fa-36-e7-34
>     modelName: AS25PBAHRA
>     nickName: Büro
>     sections:
>       chatbot: True
>       double_pairing_hidden: True
>       epp_enabled: False
>     serialNumber: AABF10E0000N5M7T1163
>     series: pearl
>     topics:
>       publish:
>       subscribe:
>         - $aws/events/presence/disconnected/a8-48-fa-36-e7-34
>         - $aws/events/presence/connected/a8-48-fa-36-e7-34
>         - haier/things/a8-48-fa-36-e7-34/event/appliancestatus/update
>         - haier/things/a8-48-fa-36-e7-34/event/discovery/update
>     unitConfiguration: 1toN
>   attributes:
>     activity:
>       activityExecutionStarted: 2023-08-26 19:51:51
>       activityStarted: 2023-08-26T19:51:51Z
>       applianceTypeName: AC
>       attributes:
>         10degreeHeatingStatus: 0
>         acType: 0
>         airQuality: 0
>         appVersion: 2.0.10
>         ch2oCleaningStatus: 0
>         ch2oValueIndoor: 0
>         channel: mobileApp
>         cleaningTimeStatus: 0
>         co2ValueIndoor: 0
>         compressorCurrent: 51.10
>         compressorFrequency: 0
>         compressorStatus: 0
>         defrostStatus: 0
>         deviceModel: exynos9820
>         echoStatus: 0
>         ecoMode: 0
>         electricHeatingStatus: 0
>         electricHeatingStatusIndoor: 0
>         energySavePeriod: 15
>         energySavingStatus: 0
>         errAckFlag: 0
>         expansionValveOpenDegree: 4
>         fanStatusIndoor: 0
>         fanStatusOutdoor: 2
>         filterChangeStatusCloud: 0
>         fourWayValveStatus: 2
>         freshAirStatus: 0
>         halfDegreeSettingStatus: 0
>         healthMode: 0
>         heatAccumulationStatus: 0
>         humanSensingStatus: 0
>         humidificationStatus: 0
>         humidityIndoor: 0
>         humiditySel: 30
>         intelligenceStatus: 0
>         lightStatus: 0
>         lockStatus: 0
>         machMode: 1
>         machineModeHK: 0
>         mobileOs: android
>         muteStatus: 1
>         operationSource: 3
>         origin: standardProgram
>         osVersion: 31
>         pm2p5CleaningStatus: 0
>         pm2p5LevelIndoor: 0
>         pm2p5ValueIndoor: 0
>         pm2p5ValueOutdoor: 0
>         pmvStatus: 0
>         power: 0
>         principalUserId: 0016800000Gr7dzAAB
>         programFamily: [standard]
>         rapidMode: 0
>         screenDisplayStatus: 1
>         selfCleaning56Status: 0
>         selfCleaningStatus: 0
>         sensingResult: 0
>         silentSleepStatus: 0
>         specialMode: 0
>         tempAirOutdoor: 17
>         tempCoilerIndoor: 22.00
>         tempCoilerOutdoor: 19
>         tempDefrostOutdoor: 19
>         tempInAirOutdoor: 19
>         tempIndoor: 26.00
>         tempOutdoor: 17.00
>         tempSel: 22
>         tempUnit: 0
>         vocValueIndoor: 0
>         voiceSignStatus: 0
>         voiceStatus: 0
>         windDirectionHorizontal: 0
>         windDirectionVertical: 8
>         windSensingStatus: 0
>         windSpeed: 5
>       category: CYCLE
>       macAddress: a8-48-fa-36-e7-34
>       resultCode: 0
>       ttl: 1700855511
>     commandHistory:
>       command:
>         ancillaryParameters:
>           ecoMode: 0
>           programFamily: [standard]
>           programRules: [object Object]
>           remoteActionable: 1
>           remoteVisible: 1
>         applianceOptions:
>         applianceType: AC
>         attributes:
>           channel: mobileApp
>           origin: standardProgram
>           prStr: Kühl
>         commandName: startProgram
>         device:
>           appVersion: 2.2.4
>           deviceModel: oriole
>           mobileId: c279d88a96b35adb
>           mobileOs: android
>           osVersion: 33
>         macAddress: a8-48-fa-36-e7-34
>         parameters:
>           10degreeHeatingStatus: 0
>           ch2oCleaningStatus: 0
>           cleaningTimeStatus: 0
>           dryLevel: 0
>           echoStatus: 0
>           electricHeatingStatus: 0
>           energySavePeriod: 15
>           energySavingStatus: 0
>           filterChangeStatusCloud: 0
>           freshAirStatus: 0
>           halfDegreeSettingStatus: 0
>           healthMode: 0
>           heatAccumulationStatus: 0
>           humanSensingStatus: 0
>           humidificationStatus: 0
>           humiditySel: 30
>           intelligenceStatus: 0
>           lightStatus: 0
>           lockStatus: 0
>           machMode: 1
>           muteStatus: 1
>           onOffStatus: 1
>           operationName: grSetDAC
>           pm2p5CleaningStatus: 0
>           pmvStatus: 0
>           rapidMode: 0
>           screenDisplayStatus: 0
>           selfCleaning56Status: 0
>           selfCleaningStatus: 0
>           silentSleepStatus: 1
>           specialMode: 0
>           tempSel: 22
>           tempUnit: 0
>           voiceSignStatus: 0
>           voiceStatus: 0
>           windDirectionHorizontal: 0
>           windDirectionVertical: 2
>           windSensingStatus: 0
>           windSpeed: 3
>         programName: PROGRAMS.AC.IOT_COOL
>         timestamp: 2023-08-26T19:53:54.358Z
>         transactionId: a8-48-fa-36-e7-34_2023-08-26T19:53:54.358Z
>       timestampAccepted: 2023-08-26T19:54:11.2Z
>       timestampExecuted: 2023-08-26T19:54:11.9Z
>     lastConnEvent:
>       category: CONNECTED
>       instantTime: 2023-08-26T19:40:09Z
>       macAddress: a8-48-fa-36-e7-34
>       timestampEvent: 1693078809549
>     parameters:
>       10degreeHeatingStatus: 0
>       acType: 0
>       airQuality: 0
>       ch2oCleaningStatus: 0
>       ch2oValueIndoor: 0
>       co2ValueIndoor: 0
>       compressorCurrent: 51.10
>       compressorFrequency: 35
>       compressorStatus: 1
>       debugEnabled: 0
>       defrostStatus: 0
>       echoStatus: 0
>       electricHeatingStatus: 0
>       electricHeatingStatusIndoor: 0
>       energySavePeriod: 15
>       energySavingStatus: 0
>       errAckFlag: 0
>       errCode: 0
>       errors: 00
>       expansionValveOpenDegree: 200
>       fanStatusIndoor: 1
>       fanStatusOutdoor: 2
>       filterChangeStatusLocal: 0
>       fourWayValveStatus: 2
>       freshAirStatus: 0
>       halfDegreeSettingStatus: 0
>       healthMode: 0
>       heatAccumulationStatus: 0
>       highTransRate: 1
>       humanSensingStatus: 0
>       humidificationStatus: 0
>       humidityIndoor: 0
>       humiditySel: 30
>       intelligenceStatus: 0
>       lightStatus: 0
>       lockStatus: 0
>       machMode: 1
>       machineModeHK: 0
>       muteStatus: 1
>       onOffStatus: 1
>       operationSource: 3
>       pm2p5CleaningStatus: 0
>       pm2p5LevelIndoor: 0
>       pm2p5ValueIndoor: 0
>       pm2p5ValueOutdoor: 0
>       pmvStatus: 0
>       power: 0
>       rapidMode: 0
>       screenDisplayStatus: 0
>       selfCleaning56Status: 0
>       selfCleaningStatus: 0
>       sensingResult: 0
>       silentSleepStatus: 1
>       specialMode: 0
>       statusSyncRate: 1440
>       stdTransRate: 3600
>       tempAirOutdoor: 24
>       tempCoilerIndoor: 13.00
>       tempCoilerOutdoor: 27
>       tempDefrostOutdoor: 18
>       tempInAirOutdoor: 6
>       tempIndoor: 25.00
>       tempOutdoor: 17.00
>       tempSel: 22.00
>       tempUnit: 0
>       totalElectricityUsed: 0
>       totalWorkTime: 0
>       transMode: 0
>       vocValueIndoor: 0
>       voiceSignStatus: 0
>       voiceStatus: 0
>       windDirectionHorizontal: 0
>       windDirectionVertical: 2
>       windSensingStatus: 0
>       windSpeed: 5
>     resultCode: 0
>   settings:
>     ancillaryParameters:
>       programRules: {'selfCleaningStatus': {'$installationType': {'1toN': {'typology': 'fixed', 'fixedValue': '0'}}}, 'selfCleaning56Status': {'$installationType': {'1to2': {'typology': 'fixed', 'fixedValue': '0'}, '1toN': {'typology': 'fixed', 'fixedValue': '0'}}}}
>     custom:
>       category: setParameters
>     parameters:
>       10degreeHeatingStatus: 0
>       ch2oCleaningStatus: 0
>       cleaningTimeStatus: 0
>       echoStatus: 0
>       electricHeatingStatus: 0
>       energySavePeriod: 15
>       energySavingStatus: 0
>       filterChangeStatusCloud: 0
>       freshAirStatus: 0
>       halfDegreeSettingStatus: 0
>       healthMode: 0
>       heatAccumulationStatus: 0
>       humanSensingStatus: 0
>       humidificationStatus: 0
>       humiditySel: 30
>       intelligenceStatus: 0
>       lightStatus: 0
>       lockStatus: 0
>       machMode: 0
>       muteStatus: 0
>       onOffStatus: 1
>       operationName: grSetDAC
>       pm2p5CleaningStatus: 0
>       pmvStatus: 0
>       rapidMode: 0
>       screenDisplayStatus: 1
>       selfCleaning56Status: 0
>       selfCleaningStatus: 0
>       silentSleepStatus: 0
>       specialMode: 0
>       tempSel: 22
>       tempUnit: 0
>       voiceSignStatus: 0
>       voiceStatus: 0
>       windDirectionHorizontal: 0
>       windDirectionVertical: 5
>       windSensingStatus: 0
>       windSpeed: 5
>   startProgram:
>     ancillaryParameters:
>       programRules: {'selfCleaningStatus': {'$installationType': {'1toN': {'typology': 'fixed', 'fixedValue': '0'}}}, 'selfCleaning56Status': {'$installationType': {'1to2': {'typology': 'fixed', 'fixedValue': '0'}, '1toN': {'typology': 'fixed', 'fixedValue': '0'}}}}
>       remoteActionable: 1
>       remoteVisible: 0
>     custom:
>       program: iot_simple_start
>     parameters:
>       10degreeHeatingStatus: 0
>       ch2oCleaningStatus: 0
>       cleaningTimeStatus: 0
>       echoStatus: 0
>       electricHeatingStatus: 0
>       energySavePeriod: 15
>       energySavingStatus: 0
>       filterChangeStatusCloud: 0
>       freshAirStatus: 0
>       halfDegreeSettingStatus: 0
>       healthMode: 0
>       heatAccumulationStatus: 0
>       humanSensingStatus: 0
>       humidificationStatus: 0
>       humiditySel: 30
>       intelligenceStatus: 0
>       lightStatus: 0
>       lockStatus: 0
>       machMode: 1
>       muteStatus: 1
>       onOffStatus: 1
>       operationName: grSetDAC
>       pm2p5CleaningStatus: 0
>       pmvStatus: 0
>       rapidMode: 0
>       screenDisplayStatus: 0
>       selfCleaning56Status: 0
>       selfCleaningStatus: 0
>       silentSleepStatus: 1
>       specialMode: 0
>       tempSel: 22
>       tempUnit: 0
>       voiceSignStatus: 0
>       voiceStatus: 0
>       windDirectionHorizontal: 0
>       windDirectionVertical: 2
>       windSensingStatus: 0
>       windSpeed: 3
>   statistics:
>     mostUsedPrograms:
>       - count: 12
>         prCode: None
>         programName: PROGRAMS.AC.IOT_HEAT
>       - count: 1
>         prCode: None
>         programName: PROGRAMS.AC.IOT_DRY
>     mostUsedRecipes:
>     programsCounter: 0
>   stopProgram:
>     parameters:
>       10degreeHeatingStatus: 0
>       ch2oCleaningStatus: 0
>       cleaningTimeStatus: 0
>       echoStatus: 0
>       electricHeatingStatus: 0
>       energySavePeriod: 15
>       energySavingStatus: 0
>       filterChangeStatusCloud: 0
>       freshAirStatus: 0
>       halfDegreeSettingStatus: 0
>       healthMode: 0
>       heatAccumulationStatus: 0
>       humanSensingStatus: 0
>       humidificationStatus: 0
>       humiditySel: 30
>       intelligenceStatus: 0
>       lightStatus: 0
>       lockStatus: 0
>       machMode: 0
>       muteStatus: 0
>       onOffStatus: 0
>       operationName: grSetDAC
>       pm2p5CleaningStatus: 0
>       pmvStatus: 0
>       rapidMode: 0
>       screenDisplayStatus: 1
>       selfCleaning56Status: 0
>       selfCleaningStatus: 0
>       silentSleepStatus: 0
>       specialMode: 0
>       tempSel: 22
>       tempUnit: 0
>       voiceSignStatus: 0
>       voiceStatus: 0
>       windDirectionHorizontal: 0
>       windDirectionVertical: 5
>       windSensingStatus: 0
>       windSpeed: 5
> commands:
>   settings:
>     10degreeHeatingStatus:
>       max: 1
>       min: 0
>       step: 1
>     category:
>       - setConfig
>       - setParameters
>     echoStatus:
>       max: 1
>       min: 0
>       step: 1
>     healthMode:
>       max: 1
>       min: 0
>       step: 1
>     machMode:
>       - 0
>       - 1
>       - 2
>       - 4
>       - 6
>     muteStatus:
>       max: 1
>       min: 0
>       step: 1
>     rapidMode:
>       max: 1
>       min: 0
>       step: 1
>     screenDisplayStatus:
>       max: 1
>       min: 0
>       step: 1
>     selfCleaning56Status:
>       max: 1
>       min: 0
>       step: 1
>     selfCleaningStatus:
>       max: 1
>       min: 0
>       step: 1
>     silentSleepStatus:
>       max: 1
>       min: 0
>       step: 1
>     tempSel:
>       max: 30
>       min: 16
>       step: 1
>     windDirectionVertical:
>       - 2
>       - 4
>       - 5
>       - 6
>       - 7
>       - 8
>     windSpeed:
>       - 1
>       - 2
>       - 3
>       - 5
>   startProgram:
>     10degreeHeatingStatus:
>       max: 1
>       min: 0
>       step: 1
>     echoStatus:
>       max: 1
>       min: 0
>       step: 1
>     ecoMode:
>       max: 1
>       min: 0
>       step: 1
>     healthMode:
>       max: 1
>       min: 0
>       step: 1
>     machMode:
>       - 0
>       - 1
>       - 2
>       - 4
>       - 6
>     muteStatus:
>       max: 1
>       min: 0
>       step: 1
>     program:
>       - Kühl
>       - iot_10_heating
>       - iot_auto
>       - iot_cool
>       - iot_dry
>       - iot_fan
>       - iot_heat
>       - iot_self_clean
>       - iot_self_clean_56
>       - iot_simple_start
>       - iot_uv
>       - iot_uv_and_auto
>       - iot_uv_and_cool
>       - iot_uv_and_dry
>       - iot_uv_and_fan
>       - iot_uv_and_heat
>     programFamily:
>       - maintenance
>       - health
>       - maintenance_health
>     rapidMode:
>       max: 1
>       min: 0
>       step: 1
>     remoteActionable:
>       max: 1
>       min: 0
>       step: 1
>     remoteVisible:
>       max: 1
>       min: 0
>       step: 1
>     screenDisplayStatus:
>       max: 1
>       min: 0
>       step: 1
>     selfCleaning56Status:
>       max: 1
>       min: 0
>       step: 1
>     selfCleaningStatus:
>       max: 1
>       min: 0
>       step: 1
>     silentSleepStatus:
>       max: 1
>       min: 0
>       step: 1
>     tempSel:
>       max: 30
>       min: 16
>       step: 1
>     windDirectionVertical:
>       - 2
>       - 4
>       - 5
>       - 6
>       - 7
>       - 8
>     windSpeed:
>       - 1
>       - 2
>       - 3
>       - 5
>   stopProgram:
>     10degreeHeatingStatus:
>       max: 1
>       min: 0
>       step: 1
>     echoStatus:
>       max: 1
>       min: 0
>       step: 1
>     healthMode:
>       max: 1
>       min: 0
>       step: 1
>     machMode:
>       - 0
>       - 1
>       - 2
>       - 4
>       - 6
>     muteStatus:
>       max: 1
>       min: 0
>       step: 1
>     rapidMode:
>       max: 1
>       min: 0
>       step: 1
>     screenDisplayStatus:
>       max: 1
>       min: 0
>       step: 1
>     selfCleaning56Status:
>       max: 1
>       min: 0
>       step: 1
>     selfCleaningStatus:
>       max: 1
>       min: 0
>       step: 1
>     silentSleepStatus:
>       max: 1
>       min: 0
>       step: 1
>     tempSel:
>       max: 30
>       min: 16
>       step: 1
>     windDirectionVertical:
>       - 2
>       - 4
>       - 5
>       - 6
>       - 7
>       - 8
>     windSpeed:
>       - 1
>       - 2
>       - 3
>       - 5
> rules:
>   startProgram:
>     ecoMode:
>       1:
>         machMode:
>           1:
>             tempSel: 26
>             windDirectionVertical: 3
>             windSpeed: 1
>           4:
>             tempSel: 20
>             windDirectionVertical: 3
>             windSpeed: 1

![image](https://github.com/Andre0512/hon/assets/59763011/cc30192c-5819-49ab-b70d-23788c370fdc)
![image](https://github.com/Andre0512/hon/assets/59763011/1c4d1989-c13f-48b8-8ed2-31c559c5d398)

**Comment by Gonzo-Goe** [comment]
Hey there,
i want to ask about this parameters. Are you planning to intergrate this to the Add on?
Best wishes 
Gonzo

**Comment by Andre0512** [comment]
Hi, should now work with version [`v0.10.0`](https://github.com/Andre0512/hon/releases/tag/v0.10.0)
