### ISSUE TITLE
AS20HPL1HRA and hOn app

### ISSUE THREAD

**Issue by and7ey** [Andre0512/hon#110]
AS20HPL1HRA air conditioner mentioned as supported device, but I can not add it to hOn app. The manual of AC says that it works with EVO app (and I added it there), but when I try to add it to hOn app, it says that serial number is wrong.
(there is no any problem with hOn app on my side - two other devices are added there successfully)

Since it is defined as supported by addon, I would like to understand how it was done.

**Comment by and7ey** [comment]
@Andre0512 could you please help me with this? Who reported AS20HPL1HRA as supported device?

**Comment by Andre0512** [comment]
Hi, sorry I don't know who added it (it was reported anonymously). I remove it from supported list until someone can prove otherwise...
