### ISSUE TITLE
NEW AC not provided, since today

### ISSUE THREAD

**Issue by olafkaderka** [Andre0512/hon#114]
AS35S2SF1FA-WH
Firmware: 5.15.0

AS25S2SF1FA-WH
Firmware: 5.15.0

are not working since today. They were working perfect since yestwrday and one reason to buy them (two month ago)  was the integration in HA. 

This entity is no longer provided by the integration hon. If the entity is no longer used, delete it in .....

**Comment by olafkaderka** [comment]
In the HON App they are working normal.
No Error wenn try to reload  them (integration => relad ..)
But if i delete the devices and try to configure them new, they dont appear. So  are skipped , not found or whatever.

**Comment by fcqpl** [comment]
This is probably related to this error:
```
Logger: homeassistant.components.climate
Source: custom_components/hon/hon.py:58
Integration: Klimat ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 27 września 2023 16:38:20 (2 occurrences)
Last logged: 27 września 2023 18:51:29

Error while setting up hon platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hon/climate.py", line 100, in async_setup_entry
    entity = HonACClimateEntity(hass, entry, device, description)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/climate.py", line 114, in __init__
    super().__init__(hass, entry, device, description)
  File "/config/custom_components/hon/hon.py", line 23, in __init__
    coordinator = get_coordinator(hass, device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/hon.py", line 113, in get_coordinator
    coordinator = HonCoordinator(hass, appliance)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/hon.py", line 89, in __init__
    self._info = HonInfo()
                 ^^^^^^^^^
  File "/config/custom_components/hon/hon.py", line 58, in __init__
    self._pyhon_version = pkg_resources.get_distribution("pyhon").version
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 528, in get_distribution
    dist = get_provider(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 400, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (typing-extensions 4.8.0 (/usr/local/lib/python3.11/site-packages), Requirement.parse('typing-extensions==4.7.1'), {'pyhon'})
```

I also have "This entity is no longer being provided" error.

**Comment by gpelleja** [comment]
> This is probably related to this error:
> 
> ```
> Logger: homeassistant.components.climate
> Source: custom_components/hon/hon.py:58
> Integration: Klimat ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
> First occurred: 27 września 2023 16:38:20 (2 occurrences)
> Last logged: 27 września 2023 18:51:29
> 
> Error while setting up hon platform for climate
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/config/custom_components/hon/climate.py", line 100, in async_setup_entry
>     entity = HonACClimateEntity(hass, entry, device, description)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/hon/climate.py", line 114, in __init__
>     super().__init__(hass, entry, device, description)
>   File "/config/custom_components/hon/hon.py", line 23, in __init__
>     coordinator = get_coordinator(hass, device)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/hon/hon.py", line 113, in get_coordinator
>     coordinator = HonCoordinator(hass, appliance)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/hon/hon.py", line 89, in __init__
>     self._info = HonInfo()
>                  ^^^^^^^^^
>   File "/config/custom_components/hon/hon.py", line 58, in __init__
>     self._pyhon_version = pkg_resources.get_distribution("pyhon").version
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 528, in get_distribution
>     dist = get_provider(dist)
>            ^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 400, in get_provider
>     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
>                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 968, in require
>     needed = self.resolve(parse_requirements(requirements))
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
>     dist = self._resolve_dist(
>            ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (typing-extensions 4.8.0 (/usr/local/lib/python3.11/site-packages), Requirement.parse('typing-extensions==4.7.1'), {'pyhon'})
> ```
> 
> I also have "This entity is no longer being provided" error.

Same error here

**Comment by Andre0512** [comment]
Hi, there seems to be an issue with the `typing-extensions` dependency, please try [`v0.10.0-beta.1`](https://github.com/Andre0512/hon/tree/v0.10.0-beta.1)
