### ISSUE TITLE
Fridge HSW59F18EIPT no reading from temperature sensors.

### ISSUE THREAD

**Issue by GieBek** [Andre0512/hon#115]
Hi, I bought a HAIER HSW59F18EIPT fridge, so this model is well recognized by your integration.
I just wanted to ask if the temperature values are not recognized due to the lack of sensors in the fridge or maybe something else?

![Screenshot_20230930_074436_Home Assistant.jpg](https://github.com/Andre0512/hon/assets/9890042/1fce2a5e-5fd3-4b4f-956a-15ca6befd498)

**Comment by Andre0512** [comment]
Hi @GieBek, can you share your device data? Than I can analyse this :slightly_smiling_face: 

> **Data Archive**
> For further analysis, please add your appliance data archive
> Navigate to `Settings` -> `Device & Services` -> `Haier hOn` -> _your device_ and press the _Create Data Archive_ button. 
> Then open notifications to download the data zip archive.
> To attach the file:
> * GitHub Web: Use the "Attach files by dragging & dropping, selecting or pasting them." function
> * GitHub Mobile: Upload the zip archive as image

**Comment by GieBek** [comment]
Thank you for your answer, the file is attached. 
Regards.

[ref_10188.zip](https://github.com/Andre0512/hon/files/12781075/ref_10188.zip)

**Comment by Andre0512** [comment]
The api really reports -38 ˚C only, I can't find another value. Can you see something else in the hOn app? 
I find it a bit strange, but maybe your device really doesn't expose these values.

**Comment by GieBek** [comment]
Unfortunately, there is nothing about temperatures in the application :(.
I changed different modes in the refrigerator, but each time the value -38 is on tempZ1 and tempZ2.
I wonder why this is, the system should know what the current temperature is :(.

**Comment by Andre0512** [comment]
I think there is nothing we can do if the temperature is not available via api. Seems to me more like a bug with hOn and maybe that will change with an update in the future, but at the moment I can't help you...

**Comment by bbbenji** [comment]
Similar issue here. I have fridge `HTW5618ENPT` and it shows 0 degrees.

![image](https://github.com/Andre0512/hon/assets/1678118/e66ca70a-118c-48d7-a0ce-c22d4a8d1f3e)

[ref_13495.zip](https://github.com/Andre0512/hon/files/14572546/ref_13495.zip)
