### ISSUE TITLE
HI-WA164DBI support

### ISSUE THREAD

**Issue by mazmar** [Andre0512/hon#116]
Hi, I have an appartment complex with Haier MVR and I would like to control it with hass.io but it doesn't have wifi. I see wifi module for MVR HI-WA164DBI that should enable WIFI access via some app called Haier-AC. Will it support hon? or am i SOL?

Thanks

**Comment by Andre0512** [comment]
Hi, I have looked at the module and I doubt that this is compatible with hOn and so this integration will not work. Haier has many different interfaces that are not compatible with each other...
