### ISSUE TITLE
Haier AC - define a range of temperature - keep user from putting the AC way up

### ISSUE THREAD

**Issue by sinclairfr** [Andre0512/hon#118]
Thanks for a great integration. 
I'm using it with the AC Haier Geos + 3.5KW.
My tenants are using the AC and sometimes put the AC too strong.
That would be great to be able to define a min setting for AC cold and max for AC heat.
If you tell me where I need to set this const in the code, I would happy to do it.

Many thanks

**Comment by Andre0512** [comment]
Hi, I think the cleanest solution would be to [create a thermostat template](https://www.home-assistant.io/integrations/generic_thermostat/) and set your needed min and max values. 
If you really want to patch the code, have a look at [these lines](https://github.com/Andre0512/hon/blob/main/custom_components/hon/climate.py#L161-L163).

**Comment by sinclairfr** [comment]
I tried to create a thermostat template but it needs a toggle-type of heating.
I'll stick to the hard-coded solution for now.
Many thanks!
