### ISSUE TITLE
Problem with device domain when I try add oven support

### ISSUE THREAD

**Issue by MiguelAngelLV** [Andre0512/hon#12]
Hi. I trying add oven support for hOn.

Sensor, select and binary sensors works fine with a few lines (AWESOME!!), but, I can't get switch domain works.

Using the debuger, the `async_setup_entry` method of switch.py is not called, the others domains work fine.

I don't get any error in the console. I don't know what is the problem.

I check PLATFORMS for and call `hass.config_entries.async_forward_entry_setup(entry, platform)` with switch value.

I check with your original code and I get same problem.

**Comment by Andre0512** [comment]
Hi, this is strange... I just tested it on my installation it is exactly triggered like the other PLATFORMS entries. Which home assistant version do you use?

**Comment by MiguelAngelLV** [comment]
Solved!

I reinstalled all dev enviorement and now it works.
