### ISSUE TITLE
500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by m-kubik** [Andre0512/hon#122]
After trying to add integration, instead of logon screen I get: 500 Internal Server Error Server got itself in trouble
In HomeAssitant log I see:

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 19:38:28 (3 occurrences)
Last logged: 19:38:52

Unable to install package pyhOn==0.15.9: ERROR: Cannot install pyhon==0.15.9 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.3.1 [notice] To update, run: pip install --upgrade pip

This is for latest beta release

thank you

**Comment by Andre0512** [comment]
Hi, I set the dependencies more loosely in the latest version, check it out :slightly_smiling_face:
