### ISSUE TITLE
Error adding entities for domain sensor with platform hon

### ISSUE THREAD

**Issue by Bluhme1** [Andre0512/hon#123]
Got a Hoover H-Wash 500 8kg. washing machine and get the following error.

Version hOn 0.10.1 beta 1

Version HA core 2023 11.0

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 10.11.50 (1 occurrences)
Last logged: 10.11.50

Error adding entities for domain sensor with platform hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.hw_48amc_1_s_energy_efficiency cannot be added as the entity category is set to config

Debug files:

[appliance_data.json](https://github.com/Andre0512/hon/files/13237267/appliance_data.json)
[statistics.json](https://github.com/Andre0512/hon/files/13237268/statistics.json)
[attributes.json](https://github.com/Andre0512/hon/files/13237269/attributes.json)
[command_history.json](https://github.com/Andre0512/hon/files/13237270/command_history.json)
[commands.json](https://github.com/Andre0512/hon/files/13237271/commands.json)
[maintenance.json](https://github.com/Andre0512/hon/files/13237272/maintenance.json)

**Comment by Ices-Eyes** [comment]
Same pfoblem here... :)

**Comment by Andre0512** [comment]
Hi, thanks for reporting! I kind of fixed it. With home assistant 2023.11 are sensor entities now forbidden at Config section. Up to now I had organized it so that everything that belongs to the start of a program is displayed under Config, but since this is now forbidden, I'll move it to Diagnostics until I have a better idea...
