### ISSUE TITLE
AC unit AS35PBAHRA + AS25PBAHRA No fixed fan direction setting available

### ISSUE THREAD

**Issue by NoUsername10** [Andre0512/hon#139]
**Is your feature request related to a problem? Please describe.**
No, only add a feature.

**Describe the solution you'd like**
AS35PBAHRA is supported, but does not have the vertical fan direction setting available.
The hOn app has 5 presets for this.

I would be great if it's possible to add this feature.
I also have the AS25PBAHRA (same unit but a little less effective) and that works well (besides same feature missing, vertical fan fixed position preset)

Great work bringing this to Homeassistant, i use it every day!

**Describe alternatives you've considered**
-

**Device Log**
-

**Data Archive**
-

**Update
In Homeassistant the vertical setting is disabled by default by the integration (don't know why).

To enable this you have to go to the settings and enable it.
Go to: Integration Haier hOn 
- Entities 
- Entity ID with the info "Fan direction Vertical", click this entity 
- Click on the settings icon (cog) in the new window 
- Enable this setting.
- Then wait for the setting to be enabled.

Then you have to manually add this function to your cards using the code editor.
In my case the is: 
- select.ac_livingroom_fan_direction_vertical

Or, you could setup your cards again now that this setting is available.

Anyhow, this works for me.
All the best.

**Comment by Andre0512** [comment]
Hi, thanks for the update! I don't know how the setting could be got deactivated. I checked the code but don't see an issue, maybe you deactivated it by mistake? :thinking: 
Anyway, I will close the issue for now but will come back if somebody also have this issue and it's really a bug :slightly_smiling_face:
