### ISSUE TITLE
Constant which will be removed in HA Core 2025.1.

### ISSUE THREAD

**Issue by Kfrard** [Andre0512/hon#141]
**Home Assistant Logs**
TEMP_CELSIUS was used from hon, this is a deprecated constant which will be removed in HA Core 2025.1. 
Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/Andre0512/hon/issues

**Comment by Andre0512** [comment]
Fixed! Thanks for reporting :)
