### ISSUE TITLE
Haier hon integration problems with switch and binary_sensor

### ISSUE THREAD

**Issue by vyagi** [Andre0512/hon#143]
**Describe the bug**
On 6th of January most of the entities became unavailable. Today I removed the integration and added again to my home assistant but this did not help. There are only temperature sensors and basic control for the air conditioners. What is missing are very, very useful features like:  silent mode, quiet mode, screen display and many more which I used to use extensively. Has there something changed or broken?

In the logs I can see: Unexpected exception importing platform custom_components.hon.switch
and
Unexpected exception importing platform custom_components.hon.binary_sensor

**To Reproduce**
Add integration,

**Expected behavior**
See the missing entities

**Screenshots**

**Environment (please complete the following information):**
 - Home Assistant Version: 2024.1.2
 - hOn Integration Version: 5.12

**Additional context**

**Home Assistant Logs**
Logger: homeassistant.setup
Source: setup.py:403
First occurred: 10:55:39 (2 occurrences)
Last logged: 10:55:39

Unable to prepare setup for platform 'hon.switch': Platform not found (Exception importing custom_components.hon.switch).
Unable to prepare setup for platform 'hon.binary_sensor': Platform not found (Exception importing custom_components.hon.binary_sensor).

**Device Log**
Post your device info here (if available)
1. Enable the "Show Device Info" button
_This button can be found in the diagnostic section of your device or in the entity overview if "show disabled entities" is enabled._
2. Press the button to create a notification
3. Open home assistant notifications and copy the message (Crtl+A, Ctrl+C)

**Data Archive**
For further analysis, please add your appliance data archive here (if available)
Navigate to `Settings` -> `Device & Services` -> `Haier hOn` -> _your device_ and press the _Create Data Archive_ button. 
Then open notifications to download the data zip archive.
To attach the file:
* GitHub Web: Use the "Attach files by dragging & dropping, selecting or pasting them." function
* GitHub Mobile: Upload the zip archive as image

**Comment by NoUsername10** [comment]
Hi.
I was about to submit the same thing.
Here are screenshots for the same issue.

1. Settings are greyed out.
![1](https://github.com/Andre0512/hon/assets/71009757/1ce9c2a2-ce4f-4f47-9db4-72bc4276cde4)

2. entities no longer provided
![2](https://github.com/Andre0512/hon/assets/71009757/9530d563-78c9-444e-9d6d-16dc30388585)

**Comment by vyagi** [comment]
Thank you for additional screenshots - I no longer have these entries - good that you could show them.

**Comment by NoUsername10** [comment]
No problems at all, let me know if i can be of any more help!

**Comment by Andre0512** [comment]
Hi, can you see any exceptions in the logs?

> hOn Integration Version: 5.12
Can you try, to update to current version `10.1`?

**Comment by Andre0512** [comment]
Probably the same issue as #140

**Comment by NoUsername10** [comment]
Hello.
I had 10.1 installed so the issue was on that version.

I have also tried it on HASS version:
Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.4
Frontend 20240104.0

However:
After updating to the hOn v0.11.0-beta.1 the binary switches work again (woohoo!), so perhaps something with home assistant and <= 10.1 version of the hOn integration?


All the best.

**Comment by Andre0512** [comment]
Hi, do you still have trouble with this? Can you check the logs for errors? I just tested it with the data archive of an AS25PBAHRA on the latest version and everything works :thinking: 
In order to make some progress here, it would be helpful for me to analyze any logged errors and to get an updated data.zip of the affected appliances :slightly_smiling_face:

**Comment by vyagi** [comment]
Everything works after update to 0.11.0-beta, then 0.11.0 and now it is I guess 0.12.0. Everything is fine for me

**Comment by Andre0512** [comment]
Thank you! Then I'll close this issue 🙂
