### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by shanespringer** [Andre0512/hon#15]
Getting a blocking error on this integration causing it to fail.  

I'm curious if using a gmail alias is something your codebase supports? Bolded below is the correct email that I signed up with and use in the Haier app, but I know it sometimes freaks out other things

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hon/__init__.py:32
Integration: Haier hOn (documentation, issues)
First occurred: 2:03:07 PM (2 occurrences)
Last logged: 2:03:28 PM

Error setting up entry **XXXXX+XXXXXXX@gmail.com** for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 32, in async_setup_entry
    await hon.setup()
  File "/usr/local/lib/python3.10/site-packages/pyhon/api.py", line 54, in setup
    headers=await self._headers) as resp:
  File "/usr/local/lib/python3.10/site-packages/pyhon/api.py", line 44, in _headers
    if await auth.authorize(self._email, self._password, self._mobile_id):
  File "/usr/local/lib/python3.10/site-packages/pyhon/auth.py", line 142, in authorize
    if not (url := await self._login(session, email, password, fw_uid, loaded, login_url)):
  File "/usr/local/lib/python3.10/site-packages/pyhon/auth.py", line 104, in _login
    return (await response.json())["events"][0]["attributes"]["values"]["url"]
KeyError: 'events'

**Comment by tempus2016** [comment]
#11 

https://github.com/Andre0512/hon/issues/11#issuecomment-1500860230

**Comment by Andre0512** [comment]
Hey, can you test if `v0.5.0-beta.4` also works for you? The "+" and all other special characters in mail or passwords would be encoded and shouldn't be a problem.

**Comment by shanespringer** [comment]
apologies @Andre0512 , I think I might be an idiot.  the beta version didn't resolve the issue, but I think I was also conflating the smartHQ app and the hOn app.  i'm guessing this is the source of the failure as smartHQ is available in my region and hOn is not.  please feel free to reopen if that isn't the problem, but i'm going to go ahead and close this before shamefully hanging my head :)

**Comment by Andre0512** [comment]
No problem, this is really confusing with all these apps. There is hOn, haier u+, simply-fi, wizard, smartHQ... they have some compatibilities with each other, but I have not yet understood the exact connections :smiley:

**Comment by shanespringer** [comment]
It’s a crappy boat, but the company is good
