### ISSUE TITLE
Forks will disappear

### ISSUE THREAD

**Issue by svrooij** [Andre0512/hon#155]
I see a lot of forks from this repo, in the past these where also removed when there comes an official DMCA (takedown request against GitHub).

So to actually preserve the code, you need to either clone the code locally or use the "import" feature (copy the got link of this repo, press create repo, paste the URL in the import field)
to make a disconnected fork.

**Comment by pabe40** [comment]
How can I reach them to inform that I'm looking to buy a dryer which is supported by HA. Now I shall look for another brand.

**Comment by technikker** [comment]
True, but the owner is taking down the content voluntarily themselves, I don't think github have received a DMCA, so this may not apply.  Better to be safe though.

**Comment by Lukasz032** [comment]
Let's just throw them a battle they want: issue a counter-notification, contact open-source orgs for recommendations about good lawyers, and possibly open a fundraiser to pay them.

**Comment by Andre0512** [comment]
Hi, a takedown will no longer be necessary as a cooperation with Haier could be achieved, see the [Timeline of events](https://github.com/Andre0512/hon/blob/main/takedown_timeline.md) :partying_face:  
Thank you for for all your support, the community makes this possible! :heart:
