### ISSUE TITLE
hOn saves only 5 sessions, with the use of the hOn App, this causes logouts in the app

### ISSUE THREAD

**Issue by rcmcronny** [Andre0512/hon#157]
Regarding: https://github.com/Andre0512/hon/issues/147#issuecomment-1902398621

I have this issue also and as there is no bug yet, i opened it now. Hopefully, the development will go on here. 

**Describe the bug**
The use of the hOn App (every week or so) shows me logged off, i need to login,, with the tutorials usw .. thought this was a bug, but @Andre0512 says, this could be cause of the 5 session storage on the hOn Servers. 

I skip the rest here, as the cause should be clear and a possible solution could be a save of the credentials before a HA restart, to limit the new session create.
Ping me, if i can do anything here then. 

Thanks for the good work and keep on :) 
Ronny

**Comment by Andre0512** [comment]
Fixed in the latest version :slightly_smiling_face:
