### ISSUE TITLE
Entity None - bug

### ISSUE THREAD

**Issue by Kfrard** [Andre0512/hon#165]
Entity None (<class 'custom_components.hon.climate.HonACClimateEntity'>) implements HVACMode(s): off, auto, cool, dry, heat, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/Andre0512/hon/issues 

Haier hOn v0.12.0
Core 2024.2.0
Supervisor 2024.01.1
Operating System 11.5

**Comment by Andre0512** [comment]
Fixed, thanks for reporting! :slightly_smiling_face:
