### ISSUE TITLE
 Unable to setup latest version

### ISSUE THREAD

**Issue by Joshuaharry120** [Andre0512/hon#166]
When trying to login to use my washer Dryer, I'm getting auth failure on the log viewer, yet can login on app with same information, no issues. 

Have they killed this app? 

Going to try the eariler versions if work then upgrade to v12 and see if works

**Comment by Andre0512** [comment]
Hi, Haier hasn't changed anything, we are now on good terms :slightly_smiling_face: 
Problems with authentication are occasionally reported here, it is a bit fiddly implemented at the moment. For some it helped to change the password or reinstall the integration to get it working. I hope we can make a cleaner login in the future.

**Comment by Joshuaharry120** [comment]
> Hi, Haier hasn't changed anything, we are now on good terms 🙂 Problems with authentication are occasionally reported here, it is a bit fiddly implemented at the moment. For some it helped to change the password or reinstall the integration to get it working. I hope we can make a cleaner login in the future.

will give it a go, thank you.
