### ISSUE TITLE
Not showing consumption current energy washing machine live.

### ISSUE THREAD

**Issue by schwagerik** [Andre0512/hon#173]
Hi, washing machine Haier running but currenty energy not showing on watts. Why?

![image](https://github.com/Andre0512/hon/assets/46976130/ebdafc98-298e-45fc-9608-e272d450fdb3)

Thanks!

**Comment by schwagerik** [comment]
![image](https://github.com/Andre0512/hon/assets/46976130/91d89874-f02e-40d1-a2ac-a22a3c22ddd2)

Now showed but high delay.

**Comment by Borty97** [comment]
As I know it updates every 5 minutes. I suppose it's because not to do too many API requests

**Comment by Andre0512** [comment]
Hi, I set the wrong unit, see the good explanation in #158. Is fixed now :slightly_smiling_face:
