### ISSUE TITLE
TEMP_CELSIUS warning

### ISSUE THREAD

**Issue by chronvas** [Andre0512/hon#174]
**Describe the bug**
Warning in logs with "TEMP_CELSIUS was used from hon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead"

**To Reproduce**
1. Restart HA
2. Go to logs

**Expected behavior**
The warning should not appear 

**Environment (please complete the following information):**
 Core 2024.2.2
Supervisor 2024.02.0
Operating System 11.5
Frontend 20240207.1
hon 0.10.1
 
**Home Assistant Logs**
Check `System` -> `Logs` if you can find any logs related to this integration and post it here.

**Device Log**
```
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 6:00:53 PM (1 occurrences)
Last logged: 6:00:53 PM

TEMP_CELSIUS was used from hon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/Andre0512/hon/issues
```

**Comment by Andre0512** [comment]
Hi, thanks for reporting. It's already fixed in the latest version, see #141 :slightly_smiling_face:
