### ISSUE TITLE
No device

### ISSUE THREAD

**Issue by millenniumy2k** [Andre0512/hon#18]
I have this problem: the integration is there, but it doesn't let me see the 3 conditioners I have (now I use HASSIO, on the old docker installation I see them correctly..)

<img width="383" alt="image" src="https://user-images.githubusercontent.com/8614031/231141370-7e15faed-5a73-4883-b4b9-8be88a4c90b0.png">

**Comment by Andre0512** [comment]
Hey, I think you used another integration on your old installation 🤔  
Unfortunately we don't support air conditions so far, if you send me the [pyhon data](https://github.com/Andre0512/hon#contribute), I can add the support.

**Comment by Andre0512** [comment]
We have now better support for air conditioner, please try the latest beta.
