### ISSUE TITLE
Since upgrade from 0.12 to 0.13 most air cond features are disabled

### ISSUE THREAD

**Issue by jacamac** [Andre0512/hon#185]
Since upgrade from 0.12 to 0.13 most air conditioning features are disabled. I can only control temperature and operating mode

1. Install release 0.12
2. All features of the air conditioning unit are enabled. 
<img width="364" alt="Rel 0 12" src="https://github.com/Andre0512/hon/assets/750479/4ba66c28-eb1d-4931-9ca4-85ef86624a9f">
3. Install release 0.13
4. Most features are disabled 
<img width="364" alt="Rel 0 13" src="https://github.com/Andre0512/hon/assets/750479/7ce527a7-dc55-47c0-8336-047fdc276b57">

I compared the output of pyhOn 15.15 and 16.0 and could not find any significant difference (only one was a small temperature reading that was linked to the difference between the 2 runs)

**Expected behavior**
The upgrade should not disable pictures

**Environment (please complete the following information):**
 - Home Assistant Version: 2024.4.0.dev0
 - hOn Integration Version 0.12 is ok , 0.13 has the bug
 - pyhOn Version 15.15 is ok, 16.0 has the bug

I compared the code and it is far from obvious what could cause such a difference in behavior

**Comment by jacamac** [comment]
BTW this is very likely the same issue reported here "**Just a question about a few unavailable functions #170**"

**Comment by Andre0512** [comment]
Thanks for reporting! Please try the latest beta version :slightly_smiling_face:

**Comment by jacamac** [comment]
@Andre0512 I've checked the beta version and I can confirm the issue is fixed. Thank you for fixing it so quickly.

**Comment by jm314159** [comment]
I do confirm v0.14.0-beta.6 is in total operable for my air-conditioning.
