### ISSUE TITLE
Washing machine and dryer program do not show

### ISSUE THREAD

**Issue by liquidand** [Andre0512/hon#188]
**Describe the bug**
The running program is not reported in the program attribute of dryer and washing machine. Always reporting no program. I can see that the possible status list contains all the programs.

**Environment (please complete the following information):**
 - Home Assistant Version: 2024.3.1
 - hOn Integration Version 0.13.0
 - pyhOn Version [e.g. `0.13.1`, can be found in device log]

**Comment by Andre0512** [comment]
Fixed in the latest beta release, thanks for reporting! 🙂
