### ISSUE TITLE
Disabled switch by param

### ISSUE THREAD

**Issue by MiguelAngelLV** [Andre0512/hon#28]
The active switch (on/off) must be disabled when remote control is disabled in some devices (oven, dishwasher...).

**Comment by Andre0512** [comment]
That's a good idea, I will add this 👍

**Comment by MiguelAngelLV** [comment]
I think a switch a disabled parameter and disabled_on_value could be the most useful for multiples cases

```python
HonSwitchEntityDescription(
            key="active",
            name="Oven",
            icon="mdi:toaster-oven",
            turn_on_key="startProgram",
            turn_off_key="stopProgram",
            disabled="attributes.parameters.remoteCtrValid"
            disabled_on_value="0"
        ),
```

**Comment by Andre0512** [comment]
Hi, finally fixed :slightly_smiling_face: 
I think we can go with the entity category here, because when it's not a config, it must be a control.
