### ISSUE TITLE
The integration does not show any device

### ISSUE THREAD

**Issue by jangelgon** [Andre0512/hon#3]
The integration does not show any device and does not show any error, I think it is not able to extract the data from the device or the pyhOn data does not match what is searched for in the integration.
I have checked the hon.py file and mac_address on my device with pyhOn shows macAddress.
I think that the Candy devices do not show the data in the same way as the Haier ones

This is my pyhOn output:

========== TD - Dryer ==========
data:
  appliance:
    PK: user#eu-west-1:a6f1822e-beee-44f3-a5bb-5c4cb18b53ad
    SK: app#8c-4b-14-b3-44-a1
    applianceId: 8c-4b-14-b3-44-a1#2022-11-22T19:31:28Z
    applianceModelId: 497
    applianceStatus: 1
    applianceTypeId: 8
    applianceTypeName: TD
    attributes:
      acuVersion: 4.B.0
      chipset: ESP32D0WDQ5
      dictionaryId: 197
      lang: it-IT
      uiVersion: 3.C.5
    brand: candy
    code: 31102169
    connectivity: wifi|ble
    coords:
      lat: 
      lng: 
    eepromId: 160
    eepromName: 40017062
    enrollmentDate: 2022-11-22T19:31:28.443Z
    firstEnrollment: False
    firstEnrollmentTBC: False
    fwVersion: 3.2.5
    id: 497
    lastUpdate: 2022-11-22T19:31:34Z
    macAddress: 8c-4b-14-b3-44-a1
    modelName: ROE H9A3TCEX-S
    nickName: Secadora
    purchaseDate: 2022-11-21T23:00:00.000Z
    sections:
      chatbot: True
      demo: True
      ecoDelayStart: True
      inventory: True
      snap_and_dry: True
      snap_wash: True
    serialNumber: 3110216988323391
    series: rapido
    structure: heatpump
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/8c-4b-14-b3-44-a1
        - $aws/events/presence/connected/8c-4b-14-b3-44-a1
        - haier/things/8c-4b-14-b3-44-a1/event/appliancestatus/update
        - haier/things/8c-4b-14-b3-44-a1/event/discovery/update
  attributes:
    activity:
    commandHistory:
      command:
        ancillaryParameters:
          energyLabel: 0
          functionalId: 7
          programCluster: specialCare
          programFamily: [download]
          programRules:
            dryLevel:
              opt3:
                1:
                  fixedValue: 1
                  typology: fixed
            dryTime:
              dryTimeMM:
                100:
                  fixedValue: 7
                  typology: fixed
                110:
                  fixedValue: 8
                  typology: fixed
                120:
                  fixedValue: 9
                  typology: fixed
                130:
                  fixedValue: 10
                  typology: fixed
                140:
                  fixedValue: 11
                  typology: fixed
                150:
                  fixedValue: 12
                  typology: fixed
                160:
                  fixedValue: 13
                  typology: fixed
                170:
                  fixedValue: 14
                  typology: fixed
                180:
                  fixedValue: 15
                  typology: fixed
                190:
                  fixedValue: 16
                  typology: fixed
                200:
                  fixedValue: 17
                  typology: fixed
                210:
                  fixedValue: 18
                  typology: fixed
                220:
                  fixedValue: 19
                  typology: fixed
                30:
                  fixedValue: 1
                  typology: fixed
                45:
                  fixedValue: 2
                  typology: fixed
                59:
                  fixedValue: 3
                  typology: fixed
                70:
                  fixedValue: 4
                  typology: fixed
                80:
                  fixedValue: 5
                  typology: fixed
                90:
                  fixedValue: 6
                  typology: fixed
            opt3:
              dryLevel:
                2|3|4:
                  fixedValue: 0
                  typology: fixed
          remoteActionable: 1
          remoteVisible: 1
          suggestedLoadD: 4
        applianceOptions:
          opt1: anticrease
          opt2: dryingManager
          opt3: bestIroning
          opt4: hybrid
        applianceType: TD
        attributes:
          channel: mobileApp
          energyLabel: 0
          origin: standardProgram
          prStr: Planchado Súper Fácil
        commandName: startProgram
        device:
          appVersion: 1.53.7
          deviceModel: raphael
          mobileId: fac71256645dee88
          mobileOs: android
          osVersion: 35
        macAddress: 8c-4b-14-b3-44-a1
        parameters:
          anticrease: 0
          bestIroning: 0
          checkUpStatus: 0
          delayTime: 0
          dryLevel: 1
          dryingManager: 1
          hybrid: 0
          onOffStatus: 1
          prCode: 17
          prPosition: 16
        programName: PROGRAMS.TD.IOT_DRY_EASY_IRON_COTTON
        timestamp: 2023-03-09T21:58:09.082Z
        transactionId: 8c-4b-14-b3-44-a1_2023-03-09T21:58:09.083Z
      timestampAccepted: 2023-03-09T21:58:13.9Z
      timestampExecuted: 2023-03-09T21:58:15.1Z
    lastConnEvent:
      category: DISCONNECTED
      instantTime: 2023-03-14T13:29:00Z
      macAddress: 8c-4b-14-b3-44-a1
      timestampEvent: 1678800540339
    parameters:
      anticrease: 0
      bestIroning: 0
      checkUpStatus: 0
      delayTime: 0
      doorStatus: 0
      dryCotton120: 0
      dryCotton180: 0
      dryCotton60: 0
      dryCottonBone: 0
      dryCottonHang: 23
      dryCottonIron: 0
      dryCottonMax: 0
      dryCottonStore: 1
      dryFilterStatus: 0
      dryLevel: 2
      dryLevelMgmt: 1
      drySynth120: 0
      drySynth180: 0
      drySynth60: 0
      drySynthBone: 0
      drySynthHang: 0
      drySynthIron: 0
      drySynthMax: 0
      drySynthStore: 0
      dryTime: 0
      dryingManager: 0
      errors: 00
      hybrid: 0
      machMode: 0
      opt5: 0
      opt6: 0
      opt7: 0
      opt8: 0
      prCode: 0
      prPhase: 0
      prPosition: 1
      program1: 9
      program10: 0
      program10t: 0
      program11: 8
      program11t: 99
      program12: 0
      program12t: 0
      program13: 1
      program13t: 122
      program14: 6
      program14t: 126
      program15: 0
      program15t: 0
      program16: 0
      program16t: 0
      program17: 0
      program17t: 0
      program18: 0
      program18t: 0
      program19: 0
      program19t: 0
      program1t: 59
      program2: 0
      program20: 0
      program20t: 0
      program21: 0
      program21t: 0
      program2t: 0
      program3: 0
      program3t: 0
      program4: 0
      program4t: 0
      program5: 0
      program5t: 0
      program6: 0
      program6t: 0
      program7: 0
      program7t: 0
      program8: 0
      program8t: 0
      program9: 0
      program9t: 0
      remainingTimeMM: 59
      remoteCtrValid: 0
      tumblingStatus: 0
      waterTankStatus: 0
    resultCode: 0
  pauseProgram:
    pause: 1
  resumeProgram:
    pause: 0
  startProgram:
    anticrease: 0
    bestIroning: 0
    checkUpStatus: 0
    delayTime: 0
    dryLevel: 0
    dryTime: 4
    dryingManager: 0
    hybrid: 0
    onOffStatus: 1
    prCode: 24
    prPosition: 18
    prStr: 0
    program: trainers
  statistics:
    mostUsedPrograms:
      - count: 6
        prCode: 0
        prPosition: 1
        programName: PROGRAMS.TD.DAILY_PERFECT_59_MIN
        programType: D
      - count: 3
        prCode: 0
        prPosition: 11
        programName: PROGRAMS.TD.DARKS_AND_COLOURED
        programType: D
      - count: 3
        prCode: 1
        prPosition: 14
        programName: PROGRAMS.TD.ECO
        programType: D
      - count: 1
        prCode: 2
        prPosition: 13
        programName: PROGRAMS.TD.IOT_DRY_BED_LINEN
        programType: D
    programsCounter: 23
    resultCode: 0
  stopProgram:
    onOffStatus: 0
settings:
  pauseProgram:
  resumeProgram:
  startProgram:
    delayTime:
      max: 1410
      min: 0
      step: 30
    dryTime:
      max: 9
      min: 4
      step: 1
    program:
      - daily_45_min
      - daily_perfect_59_min
      - darks_and_coloured
      - eco
      - iot_checkup
      - iot_dry_anti_mites
      - iot_dry_baby
      - iot_dry_backpacks
      - iot_dry_bathrobe
      - iot_dry_bed_linen
      - iot_dry_bed_quilt
      - iot_dry_cotton
      - iot_dry_cuddly_toys
      - iot_dry_curtains
      - iot_dry_dehumidifier
      - iot_dry_delicate_tablecloths
      - iot_dry_delicates
      - iot_dry_denim_jeans
      - iot_dry_down_jacket
      - iot_dry_duvet
      - iot_dry_easy_iron_cotton
      - iot_dry_easy_iron_synthetics
      - iot_dry_gym_fit
      - iot_dry_lingerie
      - iot_dry_mixed
      - iot_dry_playsuits
      - iot_dry_rapid_30
      - iot_dry_rapid_59
      - iot_dry_regenerates_waterproof
      - iot_dry_shirts
      - iot_dry_small_load
      - iot_dry_swimsuits_and_bikinis
      - iot_dry_synthetics
      - iot_dry_tablecloths
      - iot_dry_technical_fabrics
      - iot_dry_warm_embrace
      - iot_dry_wool
      - jeans
      - mix_and_dry
      - rapid_30
      - refresh
      - relax_creases
      - saving_30_min
      - shirts
      - small_load
      - sport_plus
      - synthetics
      - trainers
      - whites
      - woolmark
      - xxl_load
  stopProgram:

**Comment by alexandre-leites** [comment]
Hey,

It is because the only currently supported device type is "WM", and yours is "TD". You will need to edit the sensor files inside your custom components, to add the sensors for TD. 

It is pretty straight forward, just look for the py files and look for lines similar to
```
SENSORS: dict[str, tuple[SensorEntityDescription, ...]] = {
    "WM": (
            <sensors>
    )
```

Copy and paste and change to yours type:
```
SENSORS: dict[str, tuple[SensorEntityDescription, ...]] = {
    "WM": (
            <sensors>
    ),
    "TD": (
            <sensors>
    ),
```

You might need to add/remove/modify depending on the functions your machine has.

I am currently testing mine which is WD instead of WM as well.

**Comment by jangelgon** [comment]
![imagen](https://user-images.githubusercontent.com/11783056/225317236-6c92dce5-9eff-4741-b6a4-b4c593fed094.png)

**Comment by Andre0512** [comment]
Hi, a few very common attributes, which I except to be available for all devices, are populated additionally as class properties with underscore, see [here](https://github.com/Andre0512/pyhOn/blob/main/pyhon/device.py#L56).
But the most attributes are loaded dynamically and can be accessed as items (see [here](https://github.com/Andre0512/pyhOn/blob/main/pyhon/device.py#L25)) or with the get-method (see [here](https://github.com/Andre0512/pyhOn/blob/main/pyhon/device.py#L40)), so I think this i not the problem.
Mixing snake-case and camel-case is a bit confusing here, but PEP8 recommends to write properties as snake-case and haier uses camel-case for it's api, so I think this is a thing we must live with.

I take a closer look at the code tonight and will see if there is any other problem, at the moment I have no idea what it could be and it should run like described by @alexandre-leites.

**Comment by Andre0512** [comment]
Hi, I can see no reason why a device will not be created if any key can be found.
Of course many of the washing machine keys will not work with your dryer and will therefore not appear in home assistant (You would have to add the keys yourself that are relevant for your appliance). But the errors-sensor and some other should be displayed if you just replace WM with TD.

Please check if you have really replaced all WM keys with TD in all places (for testing!) and if there really no error message appears in the home assistant logs.

**Comment by jangelgon** [comment]
Work fine, thanks
