### ISSUE TITLE
Problem with sensor.pralka_haier_current_electricity_used 

### ISSUE THREAD

**Issue by mariuszs4n** [Andre0512/hon#30]
![image](https://user-images.githubusercontent.com/75074734/233465057-c52da312-02df-408c-a873-24a27b1733ad.png)
![image](https://user-images.githubusercontent.com/75074734/233465112-c8f82e3d-8ab1-469d-929a-36b150bdbc86.png)

**Comment by Andre0512** [comment]
Fixed, thanks for reporting! :slightly_smiling_face:
