### ISSUE TITLE
No control with Haier climate

### ISSUE THREAD

**Issue by ingcicala** [Andre0512/hon#32]
I used old version of HON integration ( before HACS including and with GitHub script installation) with my AS35S2SF1FA-MW3 climate and all worked .
Now I updated with HACS and It find my climate machine but it reports only FW version and it doesn't give me any control!!!
![Screenshot_20230425-075544](https://user-images.githubusercontent.com/62546009/234187465-b444c810-5f6e-4ef3-a262-1fcbab9c7b47.png)

**Comment by Andre0512** [comment]
Hi, could you send me your [device data](https://github.com/Andre0512/hon#read-out-device-data)?

**Comment by ingcicala** [comment]
Of course
What do you need ?

Il mar 25 apr 2023, 08:56 Andre Basche ***@***.***> ha
scritto:

**Comment by Andre0512** [comment]
You can do it like this:
> ### Read out device data
> If you want to make a request for adding new appliances or additional attributes and don't want to use the command line, here is how you can read out your device data.
> For every device exists a hidden button which can be used to log all info of your appliance.
> 1. Enable the "Log Device Info" button  
>    _This button can be found in the diagnostic section of your device or in the entity overview if "show disabled entities" is enabled._
> 2. Press the button
> 3. Go to Settings > System > Logs, click _load full logs_ and scroll down  
>    _The formatting is messy if you not load full logs_
> 4. Here you can find all data which can be read out via the api
>    ```yaml
>    data:
>      appliance:
>        applianceId: 12-34-56-78-90-ab#2022-10-25T19:47:11Z
>        applianceModelId: 1569 
>        ...
>    ```
> 5. Copy this data

**Comment by ingcicala** [comment]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.hon.button
Source: custom_components/hon/button.py:79
Integration: Haier hOn (documentation, issues)
First occurred: 16:24:32 (1 occurrences)
Last logged: 16:24:32

Device Info: data:  appliance:    SK_Secondary: AC#selfClean56#2022-08-02    applianceId: xx-xx-xx-xx-xx-xx#2022-06-03T20:21:05Z    applianceModelId: 305    applianceStatus: 1    applianceTypeId: 11    applianceTypeName: AC    attributes:      acuVersion: 06.26.00      chipset: 1      dictionaryId: 176      eppParserSet: 1      fwLabel: iotfw_epp      lang: it-IT      uiVersion: 06.26.00    brand: haier    connectivity: wifi|ble    eepromId: 41    eepromName: no_eeprom    enrollmentDate: 2022-06-03T20:21:05.605Z    fwVersion: 5.12.0    id: 305    lastUpdate: 2022-07-20T13:43:48Z    macAddress: xx-xx-xx-xx-xx-xx    modelName: AS35S2SF1FA-MW3    nickName: Disimpegno    purchaseDate: 2022-04-28T22:00:00.000Z    sections:      chatbot: True      double_pairing_hidden: True      epp_enabled: False    series: flexis    topics:      publish:      subscribe:        - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx        - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx        - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update        - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update    unitConfiguration: 1to2  attributes:    activity:    commandHistory:      command:        ancillaryParameters:        applianceOptions:        applianceType: AC        attributes:          channel: googleHome          origin: conversationalVoice          prStr: HOME_ASSISTANT        commandName: stopProgram        device:          appVersion: 1.54.6          deviceModel: cheetah          mobileId: a44c7b7f98c44556          mobileOs: android          osVersion: 33        macAddress: xx-xx-xx-xx-xx-xx        parameters:          onOffStatus: 0        programName: PROGRAMS.AC.HOME_ASSISTANT        timestamp: 2023-04-07T13:47:16.465Z        transactionId: xx-xx-xx-xx-xx-xx_2023-04-07T13:47:16.465Z      timestampAccepted: 2023-04-07T13:47:16.6Z      timestampExecuted: 2023-04-07T13:47:17.8Z    lastConnEvent:      category: CONNECTED      instantTime: 2023-04-24T12:58:01Z      macAddress: xx-xx-xx-xx-xx-xx      timestampEvent: 1682341081307    parameters:      10degreeHeatingStatus: 0      acType: 0      airQuality: 0      ch2oCleaningStatus: 0      ch2oValueIndoor: 0      co2ValueIndoor: 0      compressorCurrent: 51.10      compressorFrequency: 0      compressorStatus: 0      debugEnabled: 0      defrostStatus: 0      echoStatus: 0      electricHeatingStatus: 0      electricHeatingStatusIndoor: 0      energySavePeriod: 15      energySavingStatus: 0      errAckFlag: 0      errCode: 0      errors: 00      expansionValveOpenDegree: 480      fanStatusIndoor: 0      fanStatusOutdoor: 2      filterChangeStatusLocal: 0      fourWayValveStatus: 2      freshAirStatus: 0      halfDegreeSettingStatus: 0      healthMode: 0      heatAccumulationStatus: 0      highTransRate: 1      humanSensingStatus: 0      humidificationStatus: 0      humidityIndoor: 0      humiditySel: 30      intelligenceStatus: 0      lightStatus: 0      lockStatus: 0      machMode: 4      machineModeHK: 0      muteStatus: 0      onOffStatus: 0      operationName:      operationSource: 0      pm2p5CleaningStatus: 0      pm2p5LevelIndoor: 0      pm2p5ValueIndoor: 0      pm2p5ValueOutdoor: 0      pmvStatus: 0      power: 0      rapidMode: 0      screenDisplayStatus: 1      selfCleaning56Status: 0      selfCleaningStatus: 0      sensingResult: 0      silentSleepStatus: 0      specialMode: 0      statusSyncRate: 1440      stdTransRate: 3600      tempAirOutdoor: 20      tempCoilerIndoor: 21.00      tempCoilerOutdoor: 18      tempDefrostOutdoor: 18      tempInAirOutdoor: 18      tempIndoor: 22.50      tempOutdoor: 19.00      tempSel: 26.00      tempUnit: 0      totalElectricityUsed: 0      totalWorkTime: 0      transMode: 0      vocValueIndoor: 0      voiceSignStatus: 0      voiceStatus: 0      windDirectionHorizontal: 3      windDirectionVertical: 7      windSensingStatus: 0      windSpeed: 1    resultCode: 0  startProgram:    10degreeHeatingStatus: 0    ch2oCleaningStatus: 1    cleaningTimeStatus: 0    echoStatus: 0    electricHeatingStatus: 0    energySavePeriod: 15    energySavingStatus: 0    filterChangeStatusCloud: 0    freshAirStatus: 0    halfDegreeSettingStatus: 0    healthMode: 1    heatAccumulationStatus: 0    humanSensingStatus: 0    humidificationStatus: 0    humiditySel: 30    intelligenceStatus: 0    lightStatus: 0    lockStatus: 0    machMode: 6    muteStatus: 0    onOffStatus: 1    operationName: grSetDAC    pm2p5CleaningStatus: 1    pmvStatus: 0    program: iot_uv_and_fan    programFamily: [health|uv]    rapidMode: 0    remoteActionable: 1    remoteVisible: 1    screenDisplayStatus: 1    selfCleaning56Status: 0    selfCleaningStatus: 0    silentSleepStatus: 0    specialMode: 0    tempSel: 22    tempUnit: 0    voiceSignStatus: 0    voiceStatus: 0    windDirectionHorizontal: 0    windDirectionVertical: 5    windSensingStatus: 0    windSpeed: 3  statistics:    mostUsedPrograms:      - count: 5        prCode: None        programName: PROGRAMS.AC.IOT_COOL      - count: 4        prCode: None        programName: PROGRAMS.AC.IOT_FAN    mostUsedRecipes:    programsCounter: 0  stopProgram:    10degreeHeatingStatus: 0    ch2oCleaningStatus: 0    cleaningTimeStatus: 0    echoStatus: 0    electricHeatingStatus: 0    energySavePeriod: 15    energySavingStatus: 0    filterChangeStatusCloud: 0    freshAirStatus: 0    halfDegreeSettingStatus: 0    healthMode: 0    heatAccumulationStatus: 0    humanSensingStatus: 0    humidificationStatus: 0    humiditySel: 30    intelligenceStatus: 0    lightStatus: 0    lockStatus: 0    machMode: 0    muteStatus: 0    onOffStatus: 0    operationName: grSetDAC    pm2p5CleaningStatus: 0    pmvStatus: 0    rapidMode: 0    screenDisplayStatus: 1    selfCleaning56Status: 0    selfCleaningStatus: 0    silentSleepStatus: 0    specialMode: 0    tempSel: 22    tempUnit: 0    voiceSignStatus: 0    voiceStatus: 0    windDirectionHorizontal: 0    windDirectionVertical: 5    windSensingStatus: 0    windSpeed: 5 commands:  startProgram:    10degreeHeatingStatus:      max: 1      min: 0      step: 1    echoStatus:      max: 1      min: 0      step: 1    ecoMode:      max: 1      min: 0      step: 1    healthMode:      max: 1      min: 0      step: 1    humanSensingStatus:      max: 3      min: 0      step: 1    machMode:      - 0      - 1      - 2      - 4      - 6    muteStatus:      max: 1      min: 0      step: 1    program:      - iot_10_heating      - iot_auto      - iot_cool      - iot_dry      - iot_fan      - iot_heat      - iot_self_clean      - iot_self_clean_56      - iot_simple_start      - iot_uv      - iot_uv_and_auto      - iot_uv_and_cool      - iot_uv_and_dry      - iot_uv_and_fan      - iot_uv_and_heat    programFamily:      - standard    rapidMode:      max: 1      min: 0      step: 1    screenDisplayStatus:      max: 1      min: 0      step: 1    selfCleaning56Status:      max: 1      min: 0      step: 1    selfCleaningStatus:      max: 1      min: 0      step: 1    silentSleepStatus:      max: 1      min: 0      step: 1    tempSel:      max: 30      min: 16      step: 1    windDirectionHorizontal:      - 0      - 3      - 4      - 5      - 6      - 7    windDirectionVertical:      - 2      - 4      - 5      - 6      - 7      - 8    windSpeed:      - 1      - 2      - 3      - 5  stopProgram:    10degreeHeatingStatus:      max: 1      min: 0      step: 1    echoStatus:      max: 1      min: 0      step: 1    healthMode:      max: 1      min: 0      step: 1    humanSensingStatus:      max: 3      min: 0      step: 1    machMode:      - 0      - 1      - 2      - 4      - 6    muteStatus:      max: 1      min: 0      step: 1    rapidMode:      max: 1      min: 0      step: 1    screenDisplayStatus:      max: 1      min: 0      step: 1    selfCleaning56Status:      max: 1      min: 0      step: 1    selfCleaningStatus:      max: 1      min: 0      step: 1    silentSleepStatus:      max: 1      min: 0      step: 1    tempSel:      max: 30      min: 16      step: 1    windDirectionHorizontal:      - 0      - 3      - 4      - 5      - 6      - 7    windDirectionVertical:      - 2      - 4      - 5      - 6      - 7      - 8    windSpeed:      - 1      - 2      - 3      - 5

**Comment by Andre0512** [comment]
Please checkout if you still have problems in the latest version :slightly_smiling_face:
