### ISSUE TITLE
Question about hOn account

### ISSUE THREAD

**Issue by houchenyu** [Andre0512/hon#33]
Sorry to bother you. I am confused about the hOn account.  
Because the account in the app is a telephone number rather email address. 
I get an error if I enter my telephone and password.
So I wonder how to get the hOn account. Thanks

**Comment by Andre0512** [comment]
That's probably the same error as #37

**Comment by Andre0512** [comment]
Hey @houchenyu, for #37 the problem seems to be an appliance that was [produced for a different market](https://github.com/Andre0512/hon/issues/37#issuecomment-1538739946).
I think that's also be the problem here. Please reopen if I'm wrong :slightly_smiling_face:
