### ISSUE TITLE
Feature Request: flag enums as enums with option list

### ISSUE THREAD

**Issue by thegareth** [Andre0512/hon#35]
Hello,

Thanks for this integration.

I tried to set an automation that fired when the machine was `Finished` but it didn't fire, and I realised it was because it was actually an enum under the hood, that HA hides very well.

By declaring the device class as an enum, and including the available values in options, HA displays the values in the dropdown and automations can be set against the translated label

This was my local mod I made, that seems to work.

```
        SensorEntityDescription(
            device_class=SensorDeviceClass.ENUM,
            key="machMode",
            name="Machine Status",
            icon="mdi:information",
            translation_key="mode",
            options=["0","1","2","3","5","6","7"]
        ),
```

**Comment by Andre0512** [comment]
Hey, thanks for the hint! That's very useful :smiley:
