### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by hgl0110** [Andre0512/hon#37]
Can't login

Logger: homeassistant.config_entries
Source: custom_components/hon/__init__.py:31
Integration: Haier hOn (documentation, issues)
First occurred: 22:31:35 (1 occurrences)
Last logged: 22:31:35

Error setting up entry 18664629847 for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 31, in async_setup_entry
    hon = await Hon(
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 41, in create
    await self.setup()
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 63, in setup
    for appliance in (await self.api.load_appliances())["payload"]["appliances"]:
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/api.py", line 69, in load_appliances
    async with self._hon.get(f"{const.API_URL}/commands/v1/appliance") as resp:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/handler/base.py", line 44, in get
    async with self._intercept(self._session.get, *args, **kwargs) as response:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/handler/hon.py", line 58, in _intercept
    kwargs["headers"] = await self._check_headers(kwargs.get("headers", {}))
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/handler/hon.py", line 49, in _check_headers
    await self.auth.authenticate()
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/auth.py", line 245, in authenticate
    if not (url := await self._login()):
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/auth.py", line 182, in _login
    await self._error_logger(response)
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/auth.py", line 83, in _error_logger
    raise exceptions.HonAuthenticationError("Can't login")
pyhon.exceptions.HonAuthenticationError: Can't login

**Comment by hgl0110** [comment]
此错误来自自定义集成。

Logger: pyhon.connection.auth
Source: custom_components/hon/__init__.py:31
Integration: Haier hOn (documentation, issues)
First occurred: 22:31:35 (1 occurrences)
Last logged: 22:31:35

hOn Authentication Error 1 401 - https://he-accounts.force.com/SmartHome/setup/secur/RemoteAccessAuthorizationPage.apexp?source=CAAAAYf7xle0MDAwMDAwMDAwMDAwMDAwAAAA8uE8tcY2GNfukY6L2npXocit5IPaIOrub5lbqVL499LdAFzVQUy1m6q7M8cLSKR7GpwOYAhdyRbQqxjbed-MAy1WKvkev3ycG0QbUmR9PrRC4fbk-l2kQ6GZxXUdkr_w9J6FlfcQEnfib_yVXvYVgzHO37ESblZ3YheXK1QPegQo3KWtzQYAXxC-66Ea9-h_sW3n0blz-exUvZN9UA-grLf9GGsHq_hIZlS2exBDiG5GIuJfvzrZkk3J4DalEo79VQyYthI1sFkAG-PeALy-yfOeWNJhZKLkAA__4Q9m0kG36NDfpg2sx1T0fehMcRwy6MPTbm_pcNmWp6XNkzZEP7OgKFGY5qeoTNUCu-rIiI4SdidxFjT_NcJAny8TlnSPvSgx-lplo9I2NJvohdLt6HJbOCrbq6sO5dSd4zXXmCDab9nwF2rXvnk1eIVEOIG2ToH3JnJpne25mcgC-Lpy8lxtSaUXV4MOWFfSDS4McORxTamdeRAaFL26ElBHvDa5K3dD6K0hUAKpWy1O_d3FQGdc-dk8GlBqcBI3DOoSO4sjSR2LaDHCAuCusYGcpXnPCNYG7HnnwUFmZR9SWhXTeEFk14B0p9S2loPY093OAhTI9McFvBrcbaMC1B3rNHFRm6Ef1KkxZfzxOvOPgirdrhs7JtgWx-OWXnM5o_Xx94L7VV6pQu9-XKfPMZFlgKyBGIZ_IAJdNukRQpqkQjtyMU0%3D&display=touch 2 302 - https://he-accounts.force.com/SmartHome/s/login?display=touch&ec=302&inst=68&startURL=/SmartHome/setup/secur/RemoteAccessAuthorizationPage.apexp?source%3DCAAAAYf7xle0MDAwMDAwMDAwMDAwMDAwAAAA8uE8tcY2GNfukY6L2npXocit5IPaIOrub5lbqVL499LdAFzVQUy1m6q7M8cLSKR7GpwOYAhdyRbQqxjbed-MAy1WKvkev3ycG0QbUmR9PrRC4fbk-l2kQ6GZxXUdkr_w9J6FlfcQEnfib_yVXvYVgzHO37ESblZ3YheXK1QPegQo3KWtzQYAXxC-66Ea9-h_sW3n0blz-exUvZN9UA-grLf9GGsHq_hIZlS2exBDiG5GIuJfvzrZkk3J4DalEo79VQyYthI1sFkAG-PeALy-yfOeWNJhZKLkAA__4Q9m0kG36NDfpg2sx1T0fehMcRwy6MPTbm_pcNmWp6XNkzZEP7OgKFGY5qeoTNUCu-rIiI4SdidxFjT_NcJAny8TlnSPvSgx-lplo9I2NJvohdLt6HJbOCrbq6sO5dSd4zXXmCDab9nwF2rXvnk1eIVEOIG2ToH3JnJpne25mcgC-Lpy8lxtSaUXV4MOWFfSDS4McORxTamdeRAaFL26ElBHvDa5K3dD6K0hUAKpWy1O_d3FQGdc-dk8GlBqcBI3DOoSO4sjSR2LaDHCAuCusYGcpXnPCNYG7HnnwUFmZR9SWhXTeEFk14B0p9S2loPY093OAhTI9McFvBrcbaMC1B3rNHFRm6Ef1KkxZfzxOvOPgirdrhs7JtgWx-OWXnM5o_Xx94L7VV6pQu9-XKfPMZFlgKyBGIZ_IAJdNukRQpqkQjtyMU0%253D%26display%3Dtouch 3 301 - https://he-accounts.force.com/SmartHome/s/login/?display=touch&ec=302&inst=68&startURL=/SmartHome/setup/secur/RemoteAccessAuthorizationPage.apexp?source%3DCAAAAYf7xle0MDAwMDAwMDAwMDAwMDAwAAAA8uE8tcY2GNfukY6L2npXocit5IPaIOrub5lbqVL499LdAFzVQUy1m6q7M8cLSKR7GpwOYAhdyRbQqxjbed-MAy1WKvkev3ycG0QbUmR9PrRC4fbk-l2kQ6GZxXUdkr_w9J6FlfcQEnfib_yVXvYVgzHO37ESblZ3YheXK1QPegQo3KWtzQYAXxC-66Ea9-h_sW3n0blz-exUvZN9UA-grLf9GGsHq_hIZlS2exBDiG5GIuJfvzrZkk3J4DalEo79VQyYthI1sFkAG-PeALy-yfOeWNJhZKLkAA__4Q9m0kG36NDfpg2sx1T0fehMcRwy6MPTbm_pcNmWp6XNkzZEP7OgKFGY5qeoTNUCu-rIiI4SdidxFjT_NcJAny8TlnSPvSgx-lplo9I2NJvohdLt6HJbOCrbq6sO5dSd4zXXmCDab9nwF2rXvnk1eIVEOIG2ToH3JnJpne25mcgC-Lpy8lxtSaUXV4MOWFfSDS4McORxTamdeRAaFL26ElBHvDa5K3dD6K0hUAKpWy1O_d3FQGdc-dk8GlBqcBI3DOoSO4sjSR2LaDHCAuCusYGcpXnPCNYG7HnnwUFmZR9SWhXTeEFk14B0p9S2loPY093OAhTI9McFvBrcbaMC1B3rNHFRm6Ef1KkxZfzxOvOPgirdrhs7JtgWx-OWXnM5o_Xx94L7VV6pQu9-XKfPMZFlgKyBGIZ_IAJdNukRQpqkQjtyMU0%253D%26display%3Dtouch 4 200 - https://he-accounts.force.com/SmartHome/s/login/?language=en_US&display=touch&ec=302&inst=68&startURL=%2FSmartHome%2Fsetup%2Fsecur%2FRemoteAccessAuthorizationPage.apexp%3Fsource%3DCAAAAYf7xle0MDAwMDAwMDAwMDAwMDAwAAAA8uE8tcY2GNfukY6L2npXocit5IPaIOrub5lbqVL499LdAFzVQUy1m6q7M8cLSKR7GpwOYAhdyRbQqxjbed-MAy1WKvkev3ycG0QbUmR9PrRC4fbk-l2kQ6GZxXUdkr_w9J6FlfcQEnfib_yVXvYVgzHO37ESblZ3YheXK1QPegQo3KWtzQYAXxC-66Ea9-h_sW3n0blz-exUvZN9UA-grLf9GGsHq_hIZlS2exBDiG5GIuJfvzrZkk3J4DalEo79VQyYthI1sFkAG-PeALy-yfOeWNJhZKLkAA__4Q9m0kG36NDfpg2sx1T0fehMcRwy6MPTbm_pcNmWp6XNkzZEP7OgKFGY5qeoTNUCu-rIiI4SdidxFjT_NcJAny8TlnSPvSgx-lplo9I2NJvohdLt6HJbOCrbq6sO5dSd4zXXmCDab9nwF2rXvnk1eIVEOIG2ToH3JnJpne25mcgC-Lpy8lxtSaUXV4MOWFfSDS4McORxTamdeRAaFL26ElBHvDa5K3dD6K0hUAKpWy1O_d3FQGdc-dk8GlBqcBI3DOoSO4sjSR2LaDHCAuCusYGcpXnPCNYG7HnnwUFmZR9SWhXTeEFk14B0p9S2loPY093OAhTI9McFvBrcbaMC1B3rNHFRm6Ef1KkxZfzxOvOPgirdrhs7JtgWx-OWXnM5o_Xx94L7VV6pQu9-XKfPMZFlgKyBGIZ_IAJdNukRQpqkQjtyMU0%253D%26display%3Dtouch&System=IoT_Mobile_App&RegistrationSubChannel=hOn 5 200 - https://he-accounts.force.com/SmartHome/s/sfsites/aura?r=3&other.LightningLoginCustom.login=1 ERROR - 200 - https://he-accounts.force.com/SmartHome/s/sfsites/aura?r=3&other.LightningLoginCustom.login=1 =============== Response =============== {"actions":[{"id":"79;a","state":"SUCCESS","returnValue":"Your login attempt has failed. Make sure the username and password are correct.","error":[]}],"context":{"mode":"PROD","app":"siteforce:loginApp2","contextPath":"/SmartHome/s/sfsites","pathPrefix":"/SmartHome","fwuid":"2kszAdlijI-L2tQGa5JU9w","mlr":1,"loaded":{"APPLICATION@markup://siteforce:loginApp2":"w6PgcAWzfeqasB1PPB9vqw"},"globalValueProviders":[{"type":"$Global","values":{"eswConfigDeveloperName":{"writable":true,"defaultValue":""},"isVoiceOver":{"writable":true,"defaultValue":false},"setupAppContextId":{"writable":true,"defaultValue":""},"density":{"writable":true,"defaultValue":""},"srcdoc":{"writable":false,"defaultValue":false},"appContextId":{"writable":true,"defaultValue":""},"dynamicTypeSize":{"writable":true,"defaultValue":""}}}],"enableAccessChecks":true,"apce":1,"dns":"c","lairn":[],"laerc":[],"lav":"57","mna":{"lightning":"interop"},"lff":{"ENABLE_MIXED_SHADOW_MODE":false,"ENABLE_LIGHT_GET_ROOT_NODE_PATCH":true,"DISABLE_LIGHT_DOM_UNSCOPED_CSS":false,"ENABLE_SCOPED_CUSTOM_ELEMENT_REGISTRY":false},"arse":1,"acaf":1,"services":["markup://lightning:configProvider","markup://force:salesforceScopedModuleResolver","markup://force:ldsEngineCreator","markup://instrumentation:locatorService"]},"perfSummary":{"version":"core","request":48,"actions":{"79;a":{"total":24,"db":8}},"actionsTotal":24,"overhead":0}} ========================================

**Comment by hgl0110** [comment]
the account in the app is a telephone number rather email address.
I get an error if I enter my telephone and password.
So I wonder how to get the hOn account. Thanks

**Comment by Andre0512** [comment]
Hi, I guess the login with phone number works somehow different. I'll try to create an account with phone number and reproduce the error. How did you create your account? I only see the possibility to create accounts with email. Is this an old account? (some years old)

**Comment by hgl0110** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hgl0110** [comment]
Account created 10 years ago

**Comment by Andre0512** [comment]
Then I probably can't create an account like that anymore, at least I can't find anything about it either. 
Another possibility would be if you send me your access data [by mail](mailto:andre.basche@gmail.com) (change password before and after), then I can try to debug the error.

**Comment by wynandbooysen** [comment]
Tried to configure this, but I can only login at https://appliances.force.com/smarthq/s/login/?language=en_US - SmartHQ app for Haier appliances in Australia

Doesn't look like the https://he-accounts.force.com/SmartHome/s/login/?language=en_US login uses the same backend, manually tried to login via the browser - also fails.

**Comment by Andre0512** [comment]
I'm wondering, can you control your devices with the [hOn app](https://hon-smarthome.com/)? As far as I have seen, Haier has a lot of apps like haier u+, simply-fi, wizard and smartHQ which are for different markets. This integration is only compatible with hOn (from Haier Europe in the Play Store). I haven't analyzed the other apps because my appliances are only compatible with hOn. So I can't say how big the differences are, but as far as I have seen, the hOn app is specific for Candy, Hoover and Haier (sold in Europe I think).
