### ISSUE TITLE
Remaining Time missing

### ISSUE THREAD

**Issue by Breakingx** [Andre0512/hon#39]
Hey, Andre

I love your integration, but can you double check if there is a sensor for time remaining? For me it's missing for my washing maschine and dryer

**Comment by Andre0512** [comment]
Hi, thanks! :smiley:  
Sure I can check, what devices do you have? (brand, model)

**Comment by Breakingx** [comment]
The H-Dry 500 and H-Wash 500 by Hoover. :)

**Comment by Breakingx** [comment]
Fixed with the latest Version! Thank you very much!

**Comment by Andre0512** [comment]
Nice! Good to hear, than I fixed that unintentionally by fixing something else 😃
