### ISSUE TITLE
Log Device Info 

### ISSUE THREAD

**Issue by sonyboypatrick** [Andre0512/hon#40]
Hello,

I would like to create a request to add my fridge to the app, but I'm not able to use the "Log Device Info" button. In the past (up to 0.7.2) the attribute was unavailable, with the 0.7.3 beta its available but the click of the button leads to an error.

`2023-05-09 10:55:29.772 ERROR (MainThread) [custom_components.hon.button] Device Info:
<bound method HonAppliance.diagnose of <pyhon.appliance.HonAppliance object at 0x7f98905090>>pyhOnVersion: 0.10.6`

Best Regards

Patrick

**Comment by Andre0512** [comment]
Hi, should be fixed in `v0.7.3` thanks for reporting!

**Comment by sonyboypatrick** [comment]
This works. Nice! :)
