### ISSUE TITLE
request for new device: Haier HFW7720ENMB fridge

### ISSUE THREAD

**Issue by sonyboypatrick** [Andre0512/hon#41]
Hello Andre,

it would be very nice if you could add support for my fridge HFW7720ENMB from Haier (especially the sensors):

> data:
> ​ ​ additional_data:
> ​ ​ appliance:
> ​ ​ ​ ​ applianceId: xx-xx-xx-xx-xx-xx#2022-11-20T08:50:21Z
> ​ ​ ​ ​ applianceModelId: 867
> ​ ​ ​ ​ applianceStatus: 1
> ​ ​ ​ ​ applianceTypeId: 14
> ​ ​ ​ ​ applianceTypeName: REF
> ​ ​ ​ ​ attributes:
> ​ ​ ​ ​ ​ ​ acuVersion: 11.23.00
> ​ ​ ​ ​ ​ ​ chipset: ESP32D0WDQ5
> ​ ​ ​ ​ ​ ​ dictionaryId: 138
> ​ ​ ​ ​ ​ ​ lang: it-IT
> ​ ​ ​ ​ brand: haier
> ​ ​ ​ ​ connectivity: wifi|ble
> ​ ​ ​ ​ eepromId: 41
> ​ ​ ​ ​ eepromName: no_eeprom
> ​ ​ ​ ​ enrollmentDate: 2022-11-20T08:50:21.404Z
> ​ ​ ​ ​ firstEnrollment: True
> ​ ​ ​ ​ firstEnrollmentTBC: True
> ​ ​ ​ ​ fwVersion: 3.8.0
> ​ ​ ​ ​ id: 867
> ​ ​ ​ ​ lastUpdate: 2022-11-20T08:50:38Z
> ​ ​ ​ ​ macAddress: xx-xx-xx-xx-xx-xx
> ​ ​ ​ ​ modelName: HFW7720ENMB
> ​ ​ ​ ​ nickName: Kühlschrank
> ​ ​ ​ ​ purchaseDate: 2022-11-18T23:00:00.000Z
> ​ ​ ​ ​ sections:
> ​ ​ ​ ​ ​ ​ inside_view: True
> ​ ​ ​ ​ ​ ​ smart_check_up: True
> ​ ​ ​ ​ ​ ​ visual_my_zone_enabled: True
> ​ ​ ​ ​ series: multidoor
> ​ ​ ​ ​ topics:
> ​ ​ ​ ​ ​ ​ publish:
> ​ ​ ​ ​ ​ ​ subscribe:
> ​ ​ ​ ​ ​ ​ ​ ​ - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx
> ​ ​ ​ ​ ​ ​ ​ ​ - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx
> ​ ​ ​ ​ ​ ​ ​ ​ - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update
> ​ ​ ​ ​ ​ ​ ​ ​ - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update
> ​ ​ attributes:
> ​ ​ ​ ​ activity:
> ​ ​ ​ ​ commandHistory:
> ​ ​ ​ ​ ​ ​ command:
> ​ ​ ​ ​ ​ ​ ​ ​ ancillaryParameters:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ programRules:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ category: rule
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ tempSelZ1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @holidayMode:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: 17
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @intelligenceMode:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: 5
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @quickModeZ1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: 1
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @quickModeZ2:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: @tempSelZ1
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ tempSelZ2:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @holidayMode:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: @tempSelZ2
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @intelligenceMode:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: -18
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @quickModeZ1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: @tempSelZ2
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @quickModeZ2:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: -24
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ mandatory: 0
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ applianceOptions:
> ​ ​ ​ ​ ​ ​ ​ ​ applianceType: REF
> ​ ​ ​ ​ ​ ​ ​ ​ attributes:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ channel: mobileApp
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ origin: standardProgram
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ prStr: PROGRAMS.REF.NO_MODE_SELECTED
> ​ ​ ​ ​ ​ ​ ​ ​ commandName: startProgram
> ​ ​ ​ ​ ​ ​ ​ ​ device:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ appVersion: 1.49.6
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ deviceModel: s5e9925
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ mobileId: a175568aeb50d78e
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ mobileOs: android
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ osVersion: 33
> ​ ​ ​ ​ ​ ​ ​ ​ macAddress: xx-xx-xx-xx-xx-xx
> ​ ​ ​ ​ ​ ​ ​ ​ parameters:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ tempSelZ3: 0
> ​ ​ ​ ​ ​ ​ ​ ​ timestamp: 2022-11-25T22:22:54.476Z
> ​ ​ ​ ​ ​ ​ ​ ​ transactionId: xx-xx-xx-xx-xx-xx_2022-11-25T22:22:54.476Z
> ​ ​ ​ ​ ​ ​ timestampAccepted: 2022-11-25T22:22:57.6Z
> ​ ​ ​ ​ ​ ​ timestampExecuted: 2022-11-25T22:22:58.2Z
> ​ ​ ​ ​ lastConnEvent:
> ​ ​ ​ ​ ​ ​ category: DISCONNECTED
> ​ ​ ​ ​ ​ ​ instantTime: 2023-04-08T10:04:23Z
> ​ ​ ​ ​ ​ ​ macAddress: xx-xx-xx-xx-xx-xx
> ​ ​ ​ ​ ​ ​ timestampEvent: 1680948263208
> ​ ​ ​ ​ parameters:
> ​ ​ ​ ​ ​ ​ door2StatusZ1: 0
> ​ ​ ​ ​ ​ ​ doorStatusZ1: 0
> ​ ​ ​ ​ ​ ​ errors: 00
> ​ ​ ​ ​ ​ ​ holidayMode: 0
> ​ ​ ​ ​ ​ ​ humidityEnv: 40
> ​ ​ ​ ​ ​ ​ intelligenceMode: 0
> ​ ​ ​ ​ ​ ​ quickModeZ1: 0
> ​ ​ ​ ​ ​ ​ quickModeZ2: 0
> ​ ​ ​ ​ ​ ​ tempEnv: 23
> ​ ​ ​ ​ ​ ​ tempSelZ1: 7
> ​ ​ ​ ​ ​ ​ tempSelZ2: -18
> ​ ​ ​ ​ ​ ​ tempSelZ3: 0
> ​ ​ ​ ​ ​ ​ tempZ1: 7
> ​ ​ ​ ​ ​ ​ tempZ2: -18
> ​ ​ ​ ​ resultCode: 0
> ​ ​ settings:
> ​ ​ ​ ​ ancillaryParameters:
> ​ ​ ​ ​ ​ ​ programRules:
> ​ ​ ​ ​ ​ ​ ​ ​ tempSelZ1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @holidayMode:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: 17
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @intelligenceMode:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: 5
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @quickModeZ1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: 1
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @quickModeZ2:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: @tempSelZ1
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ tempSelZ2:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @holidayMode:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: @tempSelZ2
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @intelligenceMode:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: -18
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @quickModeZ1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: @tempSelZ2
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ @quickModeZ2:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: -24
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ custom:
> ​ ​ ​ ​ ​ ​ category: setParameters
> ​ ​ ​ ​ parameters:
> ​ ​ ​ ​ ​ ​ tempSelZ1: 5
> ​ ​ ​ ​ ​ ​ tempSelZ2: -18
> ​ ​ startProgram:
> ​ ​ ​ ​ ancillaryParameters:
> ​ ​ ​ ​ ​ ​ nameVariants: series
> ​ ​ ​ ​ ​ ​ programFamily: [dashboard]
> ​ ​ ​ ​ ​ ​ programRules:
> ​ ​ ​ ​ ​ ​ ​ ​ tempSelZ1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ intelligenceMode:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: 5
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ ​ ​ tempSelZ2:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ intelligenceMode:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ 1:
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ fixedValue: -18
> ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ typology: fixed
> ​ ​ ​ ​ ​ ​ remoteActionable: 1
> ​ ​ ​ ​ ​ ​ remoteVisible: 1
> ​ ​ ​ ​ ​ ​ zone: [fridge|freezer]
> ​ ​ ​ ​ custom:
> ​ ​ ​ ​ ​ ​ program: auto_set
> ​ ​ ​ ​ parameters:
> ​ ​ ​ ​ ​ ​ intelligenceMode: 1
> ​ ​ stopProgram:
> ​ ​ ​ ​ parameters:
> ​ ​ ​ ​ ​ ​ holidayMode: 0
> ​ ​ ​ ​ ​ ​ intelligenceMode: 0
> ​ ​ ​ ​ ​ ​ quickModeZ1: 0
> ​ ​ ​ ​ ​ ​ quickModeZ2: 0
> commands:
> ​ ​ settings:
> ​ ​ ​ ​ category:
> ​ ​ ​ ​ ​ ​ - setConfig
> ​ ​ ​ ​ ​ ​ - setParameters
> ​ ​ ​ ​ tempSelZ1:
> ​ ​ ​ ​ ​ ​ max: 9
> ​ ​ ​ ​ ​ ​ min: 1
> ​ ​ ​ ​ ​ ​ step: 1
> ​ ​ ​ ​ tempSelZ2:
> ​ ​ ​ ​ ​ ​ max: -14
> ​ ​ ​ ​ ​ ​ min: -24
> ​ ​ ​ ​ ​ ​ step: 1
> ​ ​ startProgram:
> ​ ​ ​ ​ program:
> ​ ​ ​ ​ ​ ​ - auto_set
> ​ ​ ​ ​ ​ ​ - fruit_and_veg
> ​ ​ ​ ​ ​ ​ - holiday
> ​ ​ ​ ​ ​ ​ - quick_cool
> ​ ​ ​ ​ ​ ​ - super_cool
> ​ ​ ​ ​ ​ ​ - super_freeze
> ​ ​ ​ ​ ​ ​ - zero_fresh
> ​ ​ ​ ​ programFamily:
> ​ ​ ​ ​ ​ ​ - dashboard
> ​ ​ ​ ​ zone:
> ​ ​ ​ ​ ​ ​ - vtRoom1
> ​ ​ stopProgram:
> pyhOnVersion: 0.10.6

**Comment by Andre0512** [comment]
Hey, I am not sure which way is better to deal with the multiple zones right now, I created #45 to see if anyone has a suggestion here. But currently I favor the solution with a single device  and will probably implement it that way :slightly_smiling_face:

**Comment by Andre0512** [comment]
Hey, it's ready so far, can you test the latest beta version? :slightly_smiling_face:

**Comment by sonyboypatrick** [comment]
Hello André, works great! Nice :)

**Comment by Andre0512** [comment]
Perfect :slightly_smiling_face:

**Comment by hallard** [comment]
Hi guys,
This device has 1 fridge door and 2 freezer doors, can you confirm that by design we can't detect state of freezer doors?

I'm asking because last day one of my freezer was not correctly closed and device did not beep like it does for fridge door.

**Comment by sonyboypatrick** [comment]
> Hi guys, This device has 1 fridge door and 2 freezer doors, can you confirm that by design we can't detect state of freezer doors?
> 
> I'm asking because last day one of my freezer was not correctly closed and device did not beep like it does for fridge door.

Mine doesn't beep either :) Only the fridge door status is monitored.
