### ISSUE TITLE
Connection sensor shows as connected all the time.

### ISSUE THREAD

**Issue by finalbillybong** [Andre0512/hon#43]
Two out of my three Haier appliances show as Connected all the time when powered on regardless of whether they are in remote mode or not. 

My dishwasher works as expected (Connected when in remote mode, Disconnected when not) but my tumble dryer and washing machine do not.

**Comment by Andre0512** [comment]
Hi, which entity do you mean? That the controls show as available even when the machine is not? 
This should rework anyway, I just have some thoughts about this and created discussion #44 :slightly_smiling_face:

**Comment by finalbillybong** [comment]
As you described in the issue linked the entity in the screenshot is showing as ‘Connected’ when the machine is on and not controllable as well as on and controllable.
![IMG_0613](https://github.com/Andre0512/hon/assets/24855560/d39ad770-d9f2-4362-8410-fbe344767ca8)

**Comment by Andre0512** [comment]
Fixed in the latest version :slightly_smiling_face:

**Comment by finalbillybong** [comment]
Thank you
