### ISSUE TITLE
Start washing program

### ISSUE THREAD

**Issue by Lu-Fi** [Andre0512/hon#48]
Sry, it's possible a dumb question.

But how can i start a Washing Program with Options from HomeAssistant side ?

**Comment by Andre0512** [comment]
Hey, you have a configuration section where you can configure with which settings you want to start the program 
![Screenshot_20230515_171543_Home Assistant.jpg](https://github.com/Andre0512/hon/assets/20325077/1c4c968c-4cb5-4003-8c45-15ae4d92f6b0)
and then you have the control section here
![Screenshot_20230515_171557_Home Assistant.jpg](https://github.com/Andre0512/hon/assets/20325077/81c75357-36ab-43e7-a7e7-7612ad2a2c52)
For washing machines, you have to set the hOn program on the machine, analog to the app. Then the controls become available in home assistant and you can start it 🙂
