### ISSUE TITLE
Have to reload integration to get unavailable switches and remote control sensors to update

### ISSUE THREAD

**Issue by finalbillybong** [Andre0512/hon#55]
I've installed v0.8.0-beta.5 and now when a program has finished running or HA has been restarted I need to reload the integration to get my remote control sensors to update and for my start and pause switches to become available again. 

I did try downgrading back to the current release version but the issue remains.

**Comment by Andre0512** [comment]
Hi, I think I fixed the issue in the latest version, can you please test? :slightly_smiling_face:

**Comment by finalbillybong** [comment]
Yes this is fixed in the latest version. Thanks.
