### ISSUE TITLE
Error 1 401

### ISSUE THREAD

**Issue by kisjeth** [Andre0512/hon#59]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.config_entries
Source: custom_components/hon/__init__.py:31
Integration: Haier hOn (documentation, issues)
First occurred: 21:10:08 (1 occurrences)
Last logged: 21:10:08

Error setting up entry carxxxxxxxxx@gmail.com for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 31, in async_setup_entry
    hon = await Hon(
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 61, in create
    await self.setup()
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 91, in setup
    for appliance in (await self.api.load_appliances())["payload"]["appliances"]:
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/api.py", line 69, in load_appliances
    async with self._hon.get(f"{const.API_URL}/commands/v1/appliance") as resp:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/handler/base.py", line 44, in get
    async with self._intercept(self._session.get, *args, **kwargs) as response:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/handler/hon.py", line 58, in _intercept
    kwargs["headers"] = await self._check_headers(kwargs.get("headers", {}))
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/handler/hon.py", line 49, in _check_headers
    await self.auth.authenticate()
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/auth.py", line 245, in authenticate
    if not (url := await self._login()):
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/auth.py", line 182, in _login
    await self._error_logger(response)
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/auth.py", line 83, in _error_logger
    raise exceptions.HonAuthenticationError("Can't login")
pyhon.exceptions.HonAuthenticationError: Can't login

Logger: pyhon.connection.auth
Source: custom_components/hon/__init__.py:31
Integration: Haier hOn (documentation, issues)
First occurred: 21:10:08 (1 occurrences)
Last logged: 21:10:08

hOn Authentication Error 1 401 - https://haiereurope.my.site.com/SmartHome/setup/secur/RemoteAccessAuthorizationPage.apexp?source=CAAAAYiM9yKOMDAwMDAwMDAwMDAwMDAwAAAA9BPzbVKyB3Jox9BY4ob-QImvFJ0X4dVy7NCFwLk2Nk_ccrs0QwfxpMyhpwgqeRpLsmZ7asHWqviZp9z_tAvuNiZFRm7ZeaMEdFdR5SKaBEGo30tr2-r6hi3wwh6F1eoQW46FrnJ1Titb9pkfQwDWycpUco4MbI4v5tc8IndHBUIC8yLqsVKZfS475Ho-strYxZcMyMS1JpXFFKk2fktn8NbPg5sSSB2QmjD6XKL1EUNAj4nBxsrqWxVnyYIVT85HmEA3Y43KOju_fZHSQ6mqaJTv3LwlE558gQdNckF-javd0Rdykft_4EdIW35VvSVQb5rU1R1QryZQGvezcuI-HpIyvYLkTDaTlvYOtJonLqDCeKfFMPOzcHUL-QrupCJRI3QxWilV73aWox30QiHbAzq7Ycn5TEz_gG3FxFQJB5jjuxbDEBcNJGYJmW0XxrxCB8IP0YjE-uzXONzDh6Ig8eiyzEobPAVPBf59hTdrN_S5EzUm3vFygoqNuGXHNzBLaiA_pAuk5gWOJ4pnMtePX1-i3_DbjCWejdbBUw36kKe1L8fNe1dn1ZVc2fgp74k-3rrmD70TP6p7Rq5E1R4tF4KjQycZ7a05l_ggh4D18UwxBGiR8FuxvTU6RD6eQgblgL0QV2hXasktLNTDDpnTf5Q7y6g-JbNxmbikVt672Mgt3NIcrkUEv5CPVqMQjcBUgVk012E3pi0RZ9fuJARWIXDw45felK9JSZPYG2BQoePk&display=touch 2 302 - https://haiereurope.my.site.com/SmartHome/s/login?display=touch&ec=302&inst=68&startURL=/SmartHome/setup/secur/RemoteAccessAuthorizationPage.apexp?source%3DCAAAAYiM9yKOMDAwMDAwMDAwMDAwMDAwAAAA9BPzbVKyB3Jox9BY4ob-QImvFJ0X4dVy7NCFwLk2Nk_ccrs0QwfxpMyhpwgqeRpLsmZ7asHWqviZp9z_tAvuNiZFRm7ZeaMEdFdR5SKaBEGo30tr2-r6hi3wwh6F1eoQW46FrnJ1Titb9pkfQwDWycpUco4MbI4v5tc8IndHBUIC8yLqsVKZfS475Ho-strYxZcMyMS1JpXFFKk2fktn8NbPg5sSSB2QmjD6XKL1EUNAj4nBxsrqWxVnyYIVT85HmEA3Y43KOju_fZHSQ6mqaJTv3LwlE558gQdNckF-javd0Rdykft_4EdIW35VvSVQb5rU1R1QryZQGvezcuI-HpIyvYLkTDaTlvYOtJonLqDCeKfFMPOzcHUL-QrupCJRI3QxWilV73aWox30QiHbAzq7Ycn5TEz_gG3FxFQJB5jjuxbDEBcNJGYJmW0XxrxCB8IP0YjE-uzXONzDh6Ig8eiyzEobPAVPBf59hTdrN_S5EzUm3vFygoqNuGXHNzBLaiA_pAuk5gWOJ4pnMtePX1-i3_DbjCWejdbBUw36kKe1L8fNe1dn1ZVc2fgp74k-3rrmD70TP6p7Rq5E1R4tF4KjQycZ7a05l_ggh4D18UwxBGiR8FuxvTU6RD6eQgblgL0QV2hXasktLNTDDpnTf5Q7y6g-JbNxmbikVt672Mgt3NIcrkUEv5CPVqMQjcBUgVk012E3pi0RZ9fuJARWIXDw45felK9JSZPYG2BQoePk%26display%3Dtouch 3 301 - https://haiereurope.my.site.com/SmartHome/s/login/?display=touch&ec=302&inst=68&startURL=/SmartHome/setup/secur/RemoteAccessAuthorizationPage.apexp?source%3DCAAAAYiM9yKOMDAwMDAwMDAwMDAwMDAwAAAA9BPzbVKyB3Jox9BY4ob-QImvFJ0X4dVy7NCFwLk2Nk_ccrs0QwfxpMyhpwgqeRpLsmZ7asHWqviZp9z_tAvuNiZFRm7ZeaMEdFdR5SKaBEGo30tr2-r6hi3wwh6F1eoQW46FrnJ1Titb9pkfQwDWycpUco4MbI4v5tc8IndHBUIC8yLqsVKZfS475Ho-strYxZcMyMS1JpXFFKk2fktn8NbPg5sSSB2QmjD6XKL1EUNAj4nBxsrqWxVnyYIVT85HmEA3Y43KOju_fZHSQ6mqaJTv3LwlE558gQdNckF-javd0Rdykft_4EdIW35VvSVQb5rU1R1QryZQGvezcuI-HpIyvYLkTDaTlvYOtJonLqDCeKfFMPOzcHUL-QrupCJRI3QxWilV73aWox30QiHbAzq7Ycn5TEz_gG3FxFQJB5jjuxbDEBcNJGYJmW0XxrxCB8IP0YjE-uzXONzDh6Ig8eiyzEobPAVPBf59hTdrN_S5EzUm3vFygoqNuGXHNzBLaiA_pAuk5gWOJ4pnMtePX1-i3_DbjCWejdbBUw36kKe1L8fNe1dn1ZVc2fgp74k-3rrmD70TP6p7Rq5E1R4tF4KjQycZ7a05l_ggh4D18UwxBGiR8FuxvTU6RD6eQgblgL0QV2hXasktLNTDDpnTf5Q7y6g-JbNxmbikVt672Mgt3NIcrkUEv5CPVqMQjcBUgVk012E3pi0RZ9fuJARWIXDw45felK9JSZPYG2BQoePk%26display%3Dtouch 4 200 - https://haiereurope.my.site.com/SmartHome/s/login/?language=en_US&display=touch&ec=302&inst=68&startURL=%2FSmartHome%2Fsetup%2Fsecur%2FRemoteAccessAuthorizationPage.apexp%3Fsource%3DCAAAAYiM9yKOMDAwMDAwMDAwMDAwMDAwAAAA9BPzbVKyB3Jox9BY4ob-QImvFJ0X4dVy7NCFwLk2Nk_ccrs0QwfxpMyhpwgqeRpLsmZ7asHWqviZp9z_tAvuNiZFRm7ZeaMEdFdR5SKaBEGo30tr2-r6hi3wwh6F1eoQW46FrnJ1Titb9pkfQwDWycpUco4MbI4v5tc8IndHBUIC8yLqsVKZfS475Ho-strYxZcMyMS1JpXFFKk2fktn8NbPg5sSSB2QmjD6XKL1EUNAj4nBxsrqWxVnyYIVT85HmEA3Y43KOju_fZHSQ6mqaJTv3LwlE558gQdNckF-javd0Rdykft_4EdIW35VvSVQb5rU1R1QryZQGvezcuI-HpIyvYLkTDaTlvYOtJonLqDCeKfFMPOzcHUL-QrupCJRI3QxWilV73aWox30QiHbAzq7Ycn5TEz_gG3FxFQJB5jjuxbDEBcNJGYJmW0XxrxCB8IP0YjE-uzXONzDh6Ig8eiyzEobPAVPBf59hTdrN_S5EzUm3vFygoqNuGXHNzBLaiA_pAuk5gWOJ4pnMtePX1-i3_DbjCWejdbBUw36kKe1L8fNe1dn1ZVc2fgp74k-3rrmD70TP6p7Rq5E1R4tF4KjQycZ7a05l_ggh4D18UwxBGiR8FuxvTU6RD6eQgblgL0QV2hXasktLNTDDpnTf5Q7y6g-JbNxmbikVt672Mgt3NIcrkUEv5CPVqMQjcBUgVk012E3pi0RZ9fuJARWIXDw45felK9JSZPYG2BQoePk%26display%3Dtouch&System=IoT_Mobile_App&RegistrationSubChannel=hOn 5 200 - https://haiereurope.my.site.com/SmartHome/s/sfsites/aura?r=3&other.LightningLoginCustom.login=1 ERROR - 200 - https://haiereurope.my.site.com/SmartHome/s/sfsites/aura?r=3&other.LightningLoginCustom.login=1 =============== Response =============== */{"event":{"descriptor":"markup://aura:systemError","attributes":{"values":{"message":"[AuraClientInputException from server] Unexpected request input. Expected input format: \"Data in a request must be a valid JSON Object and must be in the expected format.\".","showOverride":false}},"eventDef":{"descriptor":"markup://aura:systemError","t":"APPLICATION","xs":"G","a":{"message":["message","aura://String","G",false],"error":["error","aura://String","G",false],"auraError":["auraError","aura://Object","I",false,null],"timestamp":["timestamp","aura://Integer","I",false],"showOverride":["showOverride","aura://Boolean","I",false,false]}}},"exceptionMessage":"[AuraClientInputException from server] Unexpected request input. Expected input format: \"Data in a request must be a valid JSON Object and must be in the expected format.\".","exceptionEvent":true}/*ERROR*/ ========================================

**Comment by Giuseppe197575** [comment]
same error for me too

**Comment by kisjeth** [comment]
> I think this is the duplication of #58

May be. Let me check the #58

**Comment by kisjeth** [comment]
> I think this is the duplication of #58

Let me check the #58

**Comment by Andre0512** [comment]
Correct, this is the same error message like #58, please report any more info there :slightly_smiling_face:
