### ISSUE TITLE
Climate Wheel

### ISSUE THREAD

**Issue by Guciolek** [Andre0512/hon#62]
In the latest update, the climate wheel is not available for air conditioning.

**Comment by Andre0512** [comment]
Hi, can you check if you find it under another name? It could be that the entity was renamed with the update.

**Comment by Guciolek** [comment]
You're right. My fault. The wheel is back :D

**Comment by Andre0512** [comment]
Good to hear! Sorry didn't consider this when I refactored some code :sweat_smile:
