### ISSUE TITLE
Washing machine no longer starts.

### ISSUE THREAD

**Issue by finalbillybong** [Andre0512/hon#67]
I’m running the latest release versions with the login fix. 

My washing machine that was supported in all previous versions no longer starts. All sensors and smother functions appear to work ok though. I’ve tried to use the Show Device Info button but it does not generate anything in the logs.

**Comment by finalbillybong** [comment]
Same in latest beta

**Comment by Andre0512** [comment]
Does it work in `v0.8.0`? The fix of #63 could be the problem :thinking:

**Comment by finalbillybong** [comment]
Nope. I downgraded to 0.8.0 and it still does not work. Last release version is worked on was 0.7.3 before the login issues last week.
