### ISSUE TITLE
Readable names

### ISSUE THREAD

**Issue by tempus2016** [Andre0512/hon#68]
Is there a list of names we can correspond to numbers/id's?  As you can see below, 19 means Drying but I have no idea how to find out the others. I'd like to use the sensors on my kitchen dashboard.

Also, the icon is shown as washing machine instead of tumble dryer.
<img width="1044" alt="Screenshot 2023-06-10 at 13 59 17" src="https://github.com/Andre0512/hon/assets/40920327/c87924cc-8615-4173-b562-8699c1f1a601">
<img width="328" alt="Screenshot 2023-06-10 at 13 59 34" src="https://github.com/Andre0512/hon/assets/40920327/d7c44db5-c425-4db5-9484-f4b06e91692a">

**Comment by Andre0512** [comment]
Hi, these numbers were so ugly. I changed it now so we can use readable names. :slightly_smiling_face:

**Comment by Andre0512** [comment]
The translations can be found in the [translation json files](https://github.com/Andre0512/hon/tree/main/custom_components/hon/translations) and the corresponding numbers in the [`const.py`](https://github.com/Andre0512/hon/blob/main/custom_components/hon/const.py) but these shouldn't be interesting anymore.
