### ISSUE TITLE
Device losing it's state on some certain actions. AS50S2SF1FA-B

### ISSUE THREAD

**Issue by utegental** [Andre0512/hon#75]
**Describe the bug**
Switching between modes disables Silent / Mute / Health modes. Switching on Health mode doesn't have any effect.

**To Reproduce**

1. Switch on mode Cool.
2. Set desired temperature.
3. Select program 'UV + Cool'. That will activate Health mode.
4. See that temperature reseted to a default 22 value.
5. Set again desired temperature.
6. See that program disappeared from combobox and device switched to mode Cool(without UV).
7. Enable Mute mode.
8. Change mode to any (Fan only, for example)
9. See that Mute mode became disabled.

**Expected behavior**
Entity should preserve it's state fully, not randomly resetting some features.

**Additional context**
Looks like requests to api should be sending all the flags related to modes every time, not just when we switching them.

**Comment by Andre0512** [comment]
Hi, thanks for reporting! This was helpful to reproduce the behavior :slightly_smiling_face: 
We have some unfortunate dependencies there between the `startProgram` and `settings` commands. Please check the latest beta, I tried to improve it, but I think it still isn't perfect...

**Comment by Andre0512** [comment]
With the latest beta it should work a bit better again.
