### ISSUE TITLE
No devices showing

### ISSUE THREAD

**Issue by GrantH-H** [Andre0512/hon#82]
I have a hoover washing machine which I have added to my hoover wizard account. 

Its an H-wash 300 which is currently not on the supported list, but I was trying to follow the instructions for adding new devices. 
I added my account in the integration but i now see an integration entity that has my email address and then says no devices or entities, I see no option to show hidden or disabled devices form within the integration,  

What am I missing?

**Comment by Andre0512** [comment]
Can you control your device with the Haier hOn app? As far as I know, only newer Hoover Wizard devices are compatible with Haier hOn.

**Comment by GrantH-H** [comment]
I haven't tried the Haier hOn app, just hoover wizard.

I've just installed it and even though it accepts the same login detail no
devices in there.

I'll try adding my machine in the when I get home

**Comment by nightmare1111** [comment]
Im also not getting anything with tumble dryer, integration is showing failed to set up

**Comment by Andre0512** [comment]
@nightmare1111 which error message do you get? Please open a new issue if it's not related to Hoover wizard.

**Comment by GrantH-H** [comment]
Tried the hon app and it doesn't recognise the device serial number, so I
guess it only works in wizard.

Thanks for the fast response

**Comment by nightmare1111** [comment]
> @nightmare1111 which error message do you get? Please open a new issue if it's not related to Hoover wizard.
error message in the integration " ! Failed to set up"
im using the Haier hOn integration that links to this git hub page, do you still prefer a new issue

**Comment by Andre0512** [comment]
@nightmare1111 this sounds like a other issue than the hoover wizzard problem from Grant. Please open a new issue and share your logs.
