### ISSUE TITLE
automatically to off

### ISSUE THREAD

**Issue by wesley2004** [Andre0512/hon#86]
Since today when i press Cool or other function the airco dienst react.
After few seconds the button goed to off automatically.
i have this problem with all my 3 AC's.
Running latest beta version
I changed nothing.\
Maybe a change at HON site?

**Comment by wesley2004** [comment]
i see firmware is changed to 5.15
last week it was 5.12
maybe that's the problem?

**Comment by wesley2004** [comment]
[ac_340.zip](https://github.com/Andre0512/hon/files/11941656/ac_340.zip)

Here is my data archive

**Comment by Andre0512** [comment]
Hi, I changed some things in the latest versions, can you try to downgrade to the latest working version? :thinking: 
Can you check the logs? Also did you try to restart?

**Comment by wesley2004** [comment]
Which version can i try? It was working with latest version before!
I restart everything and can’t find any specific thing in logs

**Comment by wesley2004** [comment]
I have this message when click cool or other things
![IMG_8386](https://github.com/Andre0512/hon/assets/33071798/02dd6dc8-455e-4e73-ace4-3b18bd8cb577)

**Comment by wesley2004** [comment]
Now I deleted the complete integration.
Rebooted.
Installed again 8.1
Reboot
Now its working!
Strange but I am happy now

**Comment by Andre0512** [comment]
Strange :thinking: 
But thanks for your report, I will keep an eye on it :slightly_smiling_face:
