### ISSUE TITLE
Sensor info displayed as an integer elsewhere in the HA UI

### ISSUE THREAD

**Issue by swampylee** [Andre0512/hon#9]
Hi, the integration is great but I have a strange issue where I am displaying the machine status in a banner-card and it's showing as the value 7 but when I click that entity it is correctly showing as Finished. Is this a bug? I think I could potentially get around it by using templating in HA but I use banner-cards everywhere and these are the only sensors that do this. Same applies to Program Phase and Tumble program. Here's a screenshot.
![image](https://user-images.githubusercontent.com/52431327/229294044-028d9016-0f62-4cd9-8d44-281b6631938b.png)

**Comment by swampylee** [comment]
Found a workaround so if anyone else comes across this and uses banner-card there is at least a workaround. Use map_state on your entity as follows:

`  - color: white
    entity: sensor.garage_tumble_program_phase
    name: Program Phase
    map_state:
      '0': Waiting
      '1': "Unknown 1"
      '2': Drying
      '3': Cooldown
      '11': "Unknown 11"
  - color: white
    entity: sensor.garage_tumble_machine_status
    name: Machine Status
    map_state:
      '0': Disconnected
      '1': Ready
      '2': Running
      '3': Paused
      '4': Unknown
      '5': Scheduled
      '6': Error
      '7': Finished`

**Comment by Andre0512** [comment]
Hi, sorry for late response :sweat_smile: 
7 is the internal value and "disconnected" is the [english translation key](https://github.com/Andre0512/hon/blob/c78aeb1fbbc2bb202389fd1fa7bad2e3b1f0f0f5/custom_components/hon/translations/en.json#L16), so these banner-cards are not using the common translation functions.
If more places are reported where the untranslated values are used, we should think about working internally with the english strings as well. But I think that would make some things in the code more complex. 
I close this for now, for banner-cards, this looks like a viable workaround :slightly_smiling_face:
