### ISSUE TITLE
Set fan swing

### ISSUE THREAD

**Issue by developerGM** [Andre0512/hon#97]
Hi, I am using this fantastic custom component for my Haier Air Conditionair and I thing that need the last icing on the cake permitting to set the fan direction

Using hOn app mobile I can set 2 swing type, vertical and horizontal.
In particolar for vertical I can set 'swing' (movement) or fixed position (there are 4 fixed position) 
And for horizontal swing I can set 'swing' or 5 fixed position. 

If you need some screen or something test I can support you.

**Comment by Andre0512** [comment]
Hi, sorry it took a while :sweat_smile: 
Should now work with version [`v0.10.0`](https://github.com/Andre0512/hon/releases/tag/v0.10.0)

**Comment by developerGM** [comment]
@Andre0512 TOP!
