### ISSUE TITLE
Cannot run 0.9.0

### ISSUE THREAD

**Issue by dusan-ivanco** [Andre0512/hon#98]
**Describe the bug**
```
Setup failed for custom integration hon: Requirements for hon not found: ['pyhOn==0.14.9'].
21:56:58 – (CHYBA) setup.py
Unable to install package pyhOn==0.14.9: ERROR: Cannot install pyhon==0.14.9 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2 [notice] To update, run: pip install --upgrade pip
21:56:58 – (CHYBA) util/package.py - správa sa prvýkrát vyskytla o 21:56:30 a opakuje sa 3 krát
```

**Environment (please complete the following information):**
 - Home Assistant Version: 2023.7.3
 - hOn Integration Version: 0.9.0
 - pyhOn Version: 0.14.9

**Comment by Loeffelmaster** [comment]
Made the update to the new HA version right now and now I get the same error. :(

**Comment by Andre0512** [comment]
Please show me the output of `python - - version` and `pip freeze`

**Comment by Loeffelmaster** [comment]
These are the results.
![20230722_002739](https://github.com/Andre0512/hon/assets/15840659/0e47a236-f642-4ccb-b26f-a5118582fdf3)

**Comment by stevied65** [comment]
I have the same issue

**Comment by Giuseppe197575** [comment]
idem

**Comment by elearningdienst** [comment]
Same here after upgrade to Home Assistant 2023.7.3.

**Comment by KameDomotics** [comment]
Same issue after updating to 2023.7.3

**Comment by Andre0512** [comment]
Should be fixed in [`v0.9.1`](https://github.com/Andre0512/hon/releases/tag/v0.9.1), thanks for reporting!

**Comment by swampylee** [comment]
Thank you - seems fine now.

**Comment by Andre0512** [comment]
Thanks for testing :slightly_smiling_face:

**Comment by KameDomotics** [comment]
> Should be fixed in [`v0.9.1`](https://github.com/Andre0512/hon/releases/tag/v0.9.1), thanks for reporting!

Not working for me.
Integration not loaded, and the reload option is also missing.

![Uploading IMG_4981.jpeg…]()

**Comment by KameDomotics** [comment]
![IMG_4981](https://github.com/Andre0512/hon/assets/47695661/cfb2b9d6-29d3-4fb7-bf28-a709f562a6ed)

**Comment by swampylee** [comment]
> > Should be fixed in [`v0.9.1`](https://github.com/Andre0512/hon/releases/tag/v0.9.1), thanks for reporting!
> 
> Not working for me. Integration not loaded, and the reload option is also missing.

Did you restart home assistant? I don't think just restarting the integration works.

**Comment by KameDomotics** [comment]
> > > Should be fixed in [`v0.9.1`](https://github.com/Andre0512/hon/releases/tag/v0.9.1), thanks for reporting!
> > 
> > 
> > Not working for me. Integration not loaded, and the reload option is also missing.
> 
> Did you restart home assistant? I don't think just restarting the integration works.

Yes, I have restarted Home Assistant several times, but when I restart I get the integration not loaded notification

**Comment by KameDomotics** [comment]
Sorry, I had version 0.9.1 beta 1, now it notified me that there is official 0.9.1 (until 5 minutes ago it wasn't there...) and it works

**Comment by Doktor-X** [comment]
Works agin

**Comment by Giuseppe197575** [comment]
Work now 😊

**Comment by Loeffelmaster** [comment]
Made the update, everything is ok, also controlling the washer works. So everything fine again.
Thanks for the fast help.
